import {createLetteringEditor} from './lettering.js';
import {createControlledEdits} from './controlled-edits.js';
import {createPreviewRequests, createProjectPoller} from './preview-requests.js';
import {createPreviewGate, selectedCandidateCanAccept, imageMatchesIdentity, hasLetteringContent, refinementSource, refinementSourceMatches, abortable} from './controlled-edits-model.js';
import {ratioCrop,transformRect,originalToViewPoint} from '/engine/photo-geometry.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],token=new URLSearchParams(location.hash.slice(1)).get('token')||sessionStorage.getItem('guangjian-local-session');
if(token)sessionStorage.setItem('guangjian-local-session',token);history.replaceState(null,'',location.pathname);
let letteringEditor,controlledEdits,manualSource=null;
const previewGate=createPreviewGate(),previewRequests=createPreviewRequests();
let project,selectedCandidate=null,selectedNote=null,view='current',markMode=null,drag=null,zoom=null,pan={x:0,y:0},loadGeneration=0,imageURLs=[],noteDraft=false,localDraft=null,localDirty=false,previewVersion=null,previewReady=false,intentDraft=false,manualDraft=null,manualBase=null,exportOptions={preset:'share',format:'jpeg',maxSide:2048,quality:90},exportFile=null,intentTimer,noticeTimer,busy=false;
const labels={exposure:'曝光',contrast:'对比度',highlights:'高光',shadows:'阴影',whites:'白色色阶',blacks:'黑色色阶',warmth:'色温倾向',tint:'色调',vibrance:'自然饱和度',saturation:'饱和度',curveShadows:'曲线 · 暗部',curveMidtones:'曲线 · 中间调',curveHighlights:'曲线 · 亮部',orangeHue:'橙色 · 色相',orangeSaturation:'橙色 · 饱和度',orangeLuminance:'橙色 · 明度',greenHue:'绿色 · 色相',greenSaturation:'绿色 · 饱和度',greenLuminance:'绿色 · 明度',blueHue:'蓝色 · 色相',blueSaturation:'蓝色 · 饱和度',blueLuminance:'蓝色 · 明度',texture:'纹理',clarity:'清晰度',dehaze:'去朦胧',sharpen:'锐化',denoise:'降噪',fade:'褪色',vignette:'暗角',grain:'颗粒',monochrome:'黑白强度'};
const current=()=>project.versions.find(v=>v.id===project.currentId),candidate=()=>project.candidates.find(c=>c.id===selectedCandidate),note=()=>project.notes.find(n=>n.id===selectedNote),showing=()=>candidate()||current();
function notice(message){$('#notice').textContent=message;$('#notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').hidden=true,5500);}
async function api(route,data,signal){const response=await fetch('/api/'+route,{signal,method:data?'POST':'GET',headers:{'X-Guangjian-Token':token||'',...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});if(!response.ok){let value;try{value=await response.json();}catch{}throw Object.assign(Error(value?.error?.message||'连接暂时中断，请保留当前页面并重新连接。'),{code:value?.error?.code});}return response;}
async function json(route,data){return (await api(route,data)).json();}
async function perform(fn){if(busy||controlledEdits?.pending())return;busy=true;renderActions();let success=false;try{await fn();success=true;}catch(error){notice(error.message);if($('#versions-dialog').open){$('#restore-error').textContent=error.message;$('#restore-error').hidden=false;}await refresh(false).catch(()=>{});}finally{busy=false;renderActions();}return success;}
function chooseNewCandidate(old,next){if(selectedCandidate&&!next.candidates.some(c=>c.id===selectedCandidate))selectedCandidate=null;const added=next.candidates.filter(c=>!c.stale&&!old?.candidates.some(x=>x.id===c.id));if(added.length&&!manualDraft&&!localDirty&&!letteringEditor?.dirty())selectedCandidate=added.at(-1).id;}
function previewIdentity(){if(!project)return null;const c=candidate();return {version:view==='original'?'original':showing().id,candidateId:c?.id||null,selectionHash:view==='original'?'':c?.selectionHash||'',revision:project.revision,view,currentId:project.currentId};}
function invalidatePreview(){previewRequests.invalidate();previewReady=false;previewVersion=null;previewGate.invalidate();loadGeneration++;$('#photo-stage').classList.add('preview-outdated');$('#image-loading').hidden=false;$('#protection-layer').setAttribute('hidden','');renderActions();}
function applyProject(next){if(project&&next.revision<project.revision)return false;const old=project;project={...old,...next,candidates:next.candidates.map(c=>({...c,stale:c.stale??(c.parentId!==next.currentId||old?.candidates.find(x=>x.id===c.id)?.stale||false)}))};if(!previewGate.readyFor(previewIdentity()))invalidatePreview();return true;}
async function refresh(images=true){const next=await json('project');if(project&&next.revision<project.revision)return;const old=project;chooseNewCandidate(old,next);applyProject(next);renderState();if((images||old?.revision!==next.revision)&&!previewGate.readyFor(previewIdentity()))await loadImages();}
function node(tag,className,text){const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e;}
function renderSaveState(){$('#save-state').textContent=project.exports.some(e=>e.versionId===project.currentId)?'已导出 · 草稿已保存':project.acceptedId===project.currentId?'已接受 · 草稿已保存':'草稿已保存';$('#save-state').classList.remove('warning');}
function renderState(){
  $('#photo-name').textContent=project.source.name;$('#photo-name').title=project.source.name;renderSaveState();
  if(!intentDraft&&document.activeElement!==$('#intent-input'))$('#intent-input').value=project.intent;
  const list=$('#candidate-list');list.replaceChildren();for(const c of project.candidates){const b=node('button',c.id===selectedCandidate?'active':'',c.name);b.type='button';if(c.stale){b.append(node('small','candidate-expired','已过期'));b.title='基础版本、意图或批注已更新；可以查看，需重新试片后接受';}b.dataset.candidate=c.id;b.setAttribute('aria-pressed',String(c.id===selectedCandidate));b.addEventListener('click',()=>{if(busy||controlledEdits?.pending())return;if(manualDraft||localDirty){notice('请先试片或重置待调整参数，再切换候选。');return;}endMark();selectedCandidate=c.id;view=c.guardOperation?'current':'compare';zoom=null;pan={x:0,y:0};invalidatePreview();renderState();loadImages();});list.append(b);}
  $('#candidate-section').hidden=!project.candidates.length;$('#candidate-count').textContent=project.candidates.length+' 个方向';
  const c=candidate();$('#candidate-detail').hidden=!c;if(c){$('#candidate-name').textContent=c.name;$('#candidate-goal').textContent=c.goal||'比较当前版本与这份候选，选择更符合意图的一版。';$('#candidate-caution').textContent=[c.tradeoff,...(c.warnings||[])].filter(Boolean).join('\n')||'留意高光、肤色和局部边缘是否仍然自然。';$('#candidate-stale').hidden=!c.stale;}
  $('#next-step').textContent=c?(c.stale?'意图或批注已更新，请重新试片。':'先看完整构图，再放大检查细节。'):project.versions.length>1?'这版已保存。可以导出，也可以继续精调。':'先在 Agent 中审片，也可以从一次轻调开始。';
  const flow=project.workflowStatus,diagnosis=(project.diagnoses||[]).find(d=>d.id===flow?.diagnosisId);
  if(flow?.mode==='reviewed'&&!c?.stale)$('#next-step').textContent=flow.next;
  $('#diagnosis-section').hidden=!diagnosis;
  if(diagnosis){$('#diagnosis-goal').textContent=diagnosis.goal;$('#diagnosis-preserve').replaceChildren(...diagnosis.preserve.map(x=>node('li','',x)));const findings=$('#diagnosis-findings');findings.replaceChildren();for(const f of diagnosis.findings){const row=node('article','diagnosis-finding');row.append(node('strong','',f.area),node('p','',f.observation),node('p','quiet','检查：'+f.check));findings.append(row);}}
  if($('#edit-sources-section').open)renderEditSources();
  const review=project.reviews.at(-1);$('#review-section').hidden=!review;if(review){$('#review-summary').textContent=review.summary;$('#review-preserve').replaceChildren(...review.preserve.map(x=>node('li','',x)));}
  letteringEditor?.refresh();renderNotes();renderActions();$$('[data-view]').forEach(b=>{b.hidden=b.dataset.view==='compare'&&project.versions.length===1&&!c||b.dataset.view==='photo'&&!hasLetteringContent(showing().state);b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});
  if(!manualDraft)resetManual();
  controlledEdits?.refresh();drawMarks();
}
function renderActions(){if(!project)return;const pending=Boolean(controlledEdits?.pending()),blocked=busy||pending;for(const button of $$('#context-button,#copy-project,#intent-input,[data-view]'))button.disabled=busy;for(const button of $$('#save-note,#delete-note,#local-trial,#mark-button,#add-note,#draw-crop,#versions-button,#coordinate-note,#lettering-open'))button.disabled=blocked;const c=candidate(),ready=previewReady&&previewGate.readyFor(previewIdentity())&&previewVersion===c?.id&&view!=='photo'&&view!=='original';$('#candidate-actions').hidden=!c;$('#accept-button').disabled=blocked||noteDraft||intentDraft||Boolean(manualDraft)||localDirty||!selectedCandidateCanAccept(c,{pending,previewReady:ready});$('#accept-button').textContent=c?.guardOperation?'接受解除保护':c?.items?`接受所选 ${controlledEdits?.selectedIds().length??c.selectedItemIds?.length??0} 项`:'接受这版';$('#candidate-pending').hidden=!(c&&(manualDraft||localDirty));$('#accept-button').title=manualDraft||localDirty?'还有参数未试片，请生成试片或重置输入':pending?'正在更新所选组合':c?.noChange||c?.items&&!c.selectedItemIds?.length?'未选择实际调整，不会创建空版本':!ready?'先查看与当前选择一致的完整试片':'';$('#manual-stale').hidden=!manualDraft||refinementSourceMatches(manualSource,project);$('#discard-button').disabled=blocked;$('#trial-button').disabled=blocked;$('#export-confirm').disabled=blocked;$('#export-button').classList.toggle('primary',!c&&project.versions.length>1);$('#export-button').disabled=blocked||Boolean(c)||Boolean(manualDraft)||localDirty;$('#export-button').title=manualDraft||localDirty?'还有参数未试片，请先试片或重置输入':c?'先接受或取消试片，再导出已保存版本':'';controlledEdits?.renderActions();}
function renderNotes(){const list=$('#note-list');list.replaceChildren();$('#notes-empty').hidden=project.notes.length>0;$('#note-count').textContent=project.notes.length?String(project.notes.length):'';if(!project.notes.some(n=>n.id===selectedNote)){selectedNote=null;noteDraft=false;}
  for(const n of project.notes){const b=node('button','note-item'+(n.id===selectedNote?' active':''));b.type='button';b.dataset.note=n.id;b.append(node('b','',String(n.number)),node('span','',n.note||'已圈选，写一句你的想法'));b.addEventListener('click',()=>{if((noteDraft||localDirty)&&selectedNote!==n.id){notice('请先保存批注，或试片／重置局部参数后再切换标记。');return;}selectedNote=n.id;renderNotes();drawMarks();$('#note-text').focus();});b.addEventListener('pointerenter',()=>drawMarks(n.id));b.addEventListener('pointerleave',()=>drawMarks());list.append(b);}
  const n=note();$('#note-editor').hidden=!n;if(n){$('#note-label').textContent=`标记 ${n.number} · 你的想法`;if(!noteDraft){$('#note-text').value=n.note;$('#note-protect').checked=n.protect;}if(localDraft?.id!==n.id||(!refinementSourceMatches(localDraft.source,project)||localDraft.source.fromCandidate!==candidate()?.id)&&!localDirty)buildLocal(n);}drawMarks();}
function buildLocal(n){const saved=showing().state.locals.find(l=>l.id===n.id);localDirty=false;localDraft={id:n.id,base:project.currentId,source:refinementSource(project,showing()),settings:{...saved?.localSettings},feather:saved?.feather??.36,maskType:saved?.maskType||'rectangle'};const root=$('#local-parameters');root.replaceChildren();for(const key of ['exposure','shadows','warmth']){const range=project.parameters.find(p=>p.key===key).range,label=node('label','slider-label',labels[key]),out=node('output','',localDraft.settings[key]||0),input=node('input');label.htmlFor='local-'+key;input.id=label.htmlFor;input.type='range';input.min=range[0];input.max=range[1];input.step=key==='exposure'?.01:1;input.value=localDraft.settings[key]||0;input.addEventListener('input',()=>{localDirty=true;localDraft.settings[key]=Number(input.value);out.value=input.value;renderActions();});label.append(out);root.append(label,input);}$('#local-feather').value=localDraft.feather*100;$('#local-feather-value').value=Math.round(localDraft.feather*100)+'%';$$('[data-mask]').forEach(b=>b.classList.toggle('active',b.dataset.mask===localDraft.maskType));}
$('#local-feather').addEventListener('input',e=>{localDirty=true;localDraft.feather=Number(e.target.value)/100;$('#local-feather-value').value=e.target.value+'%';renderActions();});for(const b of $$('[data-mask]'))b.addEventListener('click',()=>{localDirty=true;localDraft.maskType=b.dataset.mask;$$('[data-mask]').forEach(x=>x.classList.toggle('active',x===b));renderActions();});
$('#local-reset').addEventListener('click',()=>{buildLocal(note());renderActions();notice('已读取这处所选版本的参数。');});
$('#local-trial').addEventListener('click',()=>perform(async()=>{if(noteDraft||intentDraft)throw Error('请先保存批注与意图，再生成局部试片。');if(!refinementSourceMatches(localDraft.source,project))throw Error('当前版本或所选组合已更新，请读取所选局部参数后再精调。');const result=await json('candidate',{revision:project.revision,baseVersion:project.currentId,fromCandidate:localDraft.source.fromCandidate,name:`标记 ${note().number} · 局部版`,locals:[{annotationId:selectedNote,settings:localDraft.settings,feather:localDraft.feather,maskType:localDraft.maskType}],goal:'只调整这处范围，保留其他已接受的效果。',tradeoff:'几何范围可能包含背景，请放大检查过渡。'});selectedCandidate=result.candidate.id;localDirty=false;view='compare';zoom=null;pan={x:0,y:0};await refresh();notice('局部试片已准备好，检查边缘后再接受。');}));
function drawMarks(active=selectedNote){const layer=$('#mark-layer');layer.replaceChildren();if(!project)return;controlledEdits?.draw({image:$('#image-b'),pane:$('#pane-b'),state:showing().state,crop:showing().state.crop,view});if(view==='compare'||markMode==='crop'||markMode==='protect'||!previewReady)return;const image=$('#image-b'),pane=$('#pane-b'),crop=view==='original'?null:showing().state.crop;if(!image.naturalWidth)return;const r=image.getBoundingClientRect(),box=pane.getBoundingClientRect();for(const n of project.notes){const rect=crop?transformRect(n.rect,p=>originalToViewPoint(p,crop,project.source.width,project.source.height)):n.rect;if(!rect)continue;const el=node('div','mark-box'+(n.id===active?' active':''));el.style.cssText=`left:${r.left-box.left+rect.x*r.width}px;top:${r.top-box.top+rect.y*r.height}px;width:${rect.width*r.width}px;height:${rect.height*r.height}px`;el.append(node('span','',n.number));layer.append(el);}}
async function imageURL(version,{size=1400,reference,withoutText=false,identity,signal}={}){const route=`image?version=${encodeURIComponent(version)}&size=${size}&revision=${identity.revision}${identity.selectionHash?'&selectionHash='+encodeURIComponent(identity.selectionHash):''}${withoutText?'&withoutText=true':''}${reference?'&reference='+encodeURIComponent(reference):''}`,response=await api(route,undefined,signal);const metadata={selectionHash:response.headers.get('X-Selection-Hash')||'',revision:response.headers.get('X-Project-Revision'),frameSpec:response.headers.get('X-Frame-Spec')};if(!imageMatchesIdentity(identity,metadata))throw Error('预览对应的项目或选择已变化，请重新读取预览。');const blob=await response.blob();if(signal?.aborted)throw Error('预览请求已取消');return {url:URL.createObjectURL(blob),limited:response.headers.get('X-Photo-Limited')==='true',...metadata};}
function decodeImage(url){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=()=>reject(Error('预览图片未能解码，请重新读取。'));image.src=url;});}
function loadImages(full=false){
  if(!project||controlledEdits?.pending())return;
  const identity=previewIdentity(),c=candidate(),selected=showing(),size=full?8192:1400,snapshotView=view;
  return previewRequests.load(identity,size,controller=>renderImages({controller,identity,c,selected,size,snapshotView,full}));
}
async function renderImages({controller,identity,c,selected,size,snapshotView,full}){
  const generation=++loadGeneration,ticket=previewGate.begin(identity);
  const timer=setTimeout(()=>controller.abort('timeout'),90000);let pair=[],installed=false;
  previewReady=false;renderActions();$('#photo-stage').classList.add('preview-outdated');$('#image-loading').hidden=false;$('#image-empty').hidden=true;$('#preview-error').hidden=true;
  const request=(version,options)=>imageURL(version,{...options,signal:controller.signal}).catch(error=>{if(!controller.signal.aborted)controller.abort(error);throw error;});
  try{
    const results=await Promise.allSettled([request(identity.version,{size,withoutText:snapshotView==='photo',identity}),snapshotView==='compare'?request(c?identity.currentId:'original',{size,reference:selected.id,identity:{...identity,selectionHash:''}}):Promise.resolve(null)]);
    pair=results.filter(x=>x.status==='fulfilled'&&x.value).map(x=>x.value);const failed=results.find(x=>x.status==='rejected');if(failed)throw controller.signal.reason instanceof Error?controller.signal.reason:failed.reason;
    await abortable(Promise.all(pair.map(x=>decodeImage(x.url))),controller.signal);
    if(generation!==loadGeneration||controller.signal.aborted||!previewGate.isCurrent(ticket,previewIdentity()))return;
    imageURLs.forEach(URL.revokeObjectURL);imageURLs=pair.map(x=>x.url);$('#image-b').src=pair[0].url;if(pair[1])$('#image-a').src=pair[1].url;installed=true;
    $('#pane-a').hidden=snapshotView!=='compare';$('#photo-panes').classList.toggle('compare',snapshotView==='compare');$('#photo-stage').classList.toggle('is-comparing',snapshotView==='compare');
    $('#pane-a .photo-tag').textContent=c?'当前 · 相同范围':'原片 · 相同范围';$('#photo-tag').textContent=snapshotView==='original'?'原片':snapshotView==='photo'?'无字 · 保留光色':c?'所选组合 · 尚未接受':current().name;
    await abortable(Promise.all([$('#image-b').decode(),...(pair[1]?[$('#image-a').decode()]:[])]),controller.signal);
    if(generation!==loadGeneration||controller.signal.aborted||!previewGate.complete(ticket,previewIdentity(),pair[0]))return;
    clearTimeout(timer);$('#image-size').textContent=`${project.source.width} × ${project.source.height}`;$('#view-caption').textContent=snapshotView==='compare'?'共享位置与倍率':'完整构图';previewVersion=identity.version;previewReady=true;$('#photo-stage').classList.remove('preview-outdated');
    await new Promise(requestAnimationFrame);if(generation!==loadGeneration||controller.signal.aborted)return;positionImages();drawMarks();
    if(full&&pair.some(x=>x.limited))notice('照片超过输出尺寸上限，当前细节预览已缩小。请让 Agent 使用完整输出的准确区域查看检查。');
    return true;
  }catch(error){
    if(generation===loadGeneration){const message=controller.signal.reason==='timeout'?'预览等待超时，请重试。':error.message;controller.abort('failed');previewReady=false;previewGate.invalidate();$('#preview-error-message').textContent=message;$('#preview-error').hidden=false;$('#image-empty').hidden=Boolean($('#image-b').getAttribute('src'));$('#view-caption').textContent='预览未更新';if($('#image-b').getAttribute('src'))$('#photo-tag').textContent='上一张预览 · 未更新';}
  }finally{clearTimeout(timer);if(!installed)pair.forEach(x=>URL.revokeObjectURL(x.url));if(generation===loadGeneration){$('#image-loading').hidden=true;renderActions();}}
}
function positionImages(){const visible=$$('.pane').filter(x=>!x.hidden),image=$('#image-b');if(!image.naturalWidth)return;const fit=Math.min(...visible.map(p=>Math.min(p.clientWidth/image.naturalWidth,p.clientHeight/image.naturalHeight)))*.95,z=zoom??fit;
  for(const p of visible){const img=p.querySelector('img');img.style.width=img.naturalWidth*z+'px';img.style.height=img.naturalHeight*z+'px';img.style.left=(p.clientWidth-img.naturalWidth*z)/2+pan.x+'px';img.style.top=(p.clientHeight-img.naturalHeight*z)/2+pan.y+'px';}
  $('#zoom-label').hidden=zoom===null;$('#zoom-label').textContent=Math.round(z*100)+'%';$('#fit-button').classList.toggle('active',zoom===null);$('#actual-button').classList.toggle('active',zoom===1);drawMarks();}
async function zoomTo(value){if(!project)return;zoom=value;pan={x:0,y:0};if(value>=1)await loadImages(true);positionImages();}
function fit(){zoom=null;pan={x:0,y:0};positionImages();}
function relativePoint(event){const r=$('#image-b').getBoundingClientRect();return {x:Math.max(0,Math.min(1,(event.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(event.clientY-r.top)/r.height))};}
async function startMark(mode='note'){if(busy||controlledEdits?.pending())return;if(noteDraft){notice('请先保存当前批注。');return;}if(mode==='crop'&&current().state.guards?.regions?.length){notice('已有画面保护，请先解除并接受预览后重新构图。');return;}if(mode==='protect'&&(candidate()||view!=='current'||!previewReady)){notice('请先查看已保存画面并等待预览完成。');return;}markMode=mode;if(mode!=='protect')view='original';fit();renderState();if(mode!=='protect')await loadImages();if(markMode!==mode)return;$('#photo-stage').classList.add('marking');$('#mark-hint').hidden=false;$('#mark-hint').textContent=mode==='crop'?'在原片上框选想保留的范围 · Esc 取消':mode==='protect'?'在已保存画面框选完整保留核心，外侧另有过渡带 · Esc 取消':'框选想讨论的地方，完成后写一句你的想法 · Esc 取消';}
function endMark(){markMode=null;$('#photo-stage').classList.remove('marking');$('#mark-hint').hidden=true;$('#draft-rect').hidden=true;}
$('#pane-b').addEventListener('pointerdown',e=>{if(e.button!==0||!previewReady)return;if(markMode){const r=$('#image-b').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;drag={kind:markMode,start:relativePoint(e)};}else drag={kind:'pan',x:e.clientX,y:e.clientY,pan:{...pan}};$('#pane-b').setPointerCapture(e.pointerId);});
$('#pane-b').addEventListener('pointermove',e=>{if(!drag||!$('#pane-b').hasPointerCapture(e.pointerId))return;if(drag.kind==='pan'){pan={x:drag.pan.x+e.clientX-drag.x,y:drag.pan.y+e.clientY-drag.y};positionImages();return;}const p=relativePoint(e),s=drag.start;drag.rect={x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),width:Math.abs(p.x-s.x),height:Math.abs(p.y-s.y)};const r=$('#image-b').getBoundingClientRect(),b=$('#pane-b').getBoundingClientRect();$('#draft-rect').hidden=false;$('#draft-rect').classList.toggle('radial',drag.kind==='protect'&&document.querySelector('[data-protection-shape=radial]').classList.contains('active'));$('#draft-rect').style.cssText=`left:${r.left-b.left+drag.rect.x*r.width}px;top:${r.top-b.top+drag.rect.y*r.height}px;width:${drag.rect.width*r.width}px;height:${drag.rect.height*r.height}px`;});
$('#pane-b').addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;if(d.kind==='pan')return;if(!d.rect||d.rect.width<.01||d.rect.height<.01){notice('范围太小，请再框选一次。');return;}const mode=markMode;endMark();if(mode==='crop'){ensureManual();manualDraft.crop=d.rect;renderCrop();$('#adjustments').open=true;notice('裁剪范围已选好，生成试片即可检查。');}else if(mode==='protect'){try{controlledEdits.setDraft(d.rect);}catch(error){notice(error.message);}}else perform(async()=>{const result=await json('note',{rect:d.rect,note:'',revision:project.revision});selectedNote=result.note.id;await refresh(false);$('#note-editor').scrollIntoView({block:'nearest',behavior:'smooth'});$('#note-text').focus();});});
$('#pane-b').addEventListener('pointercancel',()=>{drag=null;$('#draft-rect').hidden=true;});
$('#pane-a').addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={kind:'pan-a',x:e.clientX,y:e.clientY,pan:{...pan}};e.currentTarget.setPointerCapture(e.pointerId);});$('#pane-a').addEventListener('pointermove',e=>{if(drag?.kind!=='pan-a'||!e.currentTarget.hasPointerCapture(e.pointerId))return;pan={x:drag.pan.x+e.clientX-drag.x,y:drag.pan.y+e.clientY-drag.y};positionImages();});for(const type of ['pointerup','pointercancel'])$('#pane-a').addEventListener(type,()=>drag=null);
for(const p of $$('.pane')){p.addEventListener('wheel',e=>{if(markMode)return;e.preventDefault();const image=$('#image-b'),base=zoom??Math.min(p.clientWidth/image.naturalWidth,p.clientHeight/image.naturalHeight)*.95;zoom=Math.min(4,Math.max(.08,base*Math.exp(-e.deltaY*.002)));positionImages();},{passive:false});p.addEventListener('keydown',e=>{const d={ArrowLeft:[-32,0],ArrowRight:[32,0],ArrowUp:[0,-32],ArrowDown:[0,32]}[e.key];if(d){e.preventDefault();pan={x:pan.x+d[0],y:pan.y+d[1]};positionImages();}});}
function ensureManual(){if(!manualDraft){manualDraft=structuredClone(showing().state);manualBase=project.currentId;manualSource=refinementSource(project,showing());}renderActions();}
function resetManual(){manualDraft=null;manualBase=null;manualSource=null;buildAdjustments(showing().state);$('#manual-source').textContent=candidate()?`基于试片「${candidate().name}」继续精调`:`基于「${current().name}」继续精调`;}
$('#manual-reset').addEventListener('click',()=>{resetManual();renderActions();notice('已读取当前版本参数，未试片的手动输入已重置。');});
function buildAdjustments(state){const groups=[['光线与色彩',['exposure','highlights','shadows','contrast','whites','blacks','warmth','tint','vibrance','saturation']],['细节与质感',['texture','clarity','dehaze','sharpen','denoise','fade','grain','vignette','monochrome']],['曲线与分色',['curveShadows','curveMidtones','curveHighlights','orangeHue','orangeSaturation','orangeLuminance','greenHue','greenSaturation','greenLuminance','blueHue','blueSaturation','blueLuminance']]];const root=$('#adjustment-groups');root.replaceChildren();groups.forEach(([title,keys],i)=>{const group=node('details','parameter-group');group.open=i===0;group.append(node('summary','',title));for(const key of keys){const info=project.parameters.find(x=>x.key===key),label=node('label','slider-label',labels[key]);label.htmlFor='parameter-'+key;const out=node('output','',String(state.settings[key]??0));label.append(out);const input=node('input');input.id='parameter-'+key;input.type='range';input.min=info.range[0];input.max=info.range[1];input.step=key==='exposure'?.01:1;input.value=state.settings[key]??0;input.dataset.parameter=key;input.addEventListener('input',()=>{ensureManual();manualDraft.settings[key]=Number(input.value);out.value=input.value;});group.append(label,input);}root.append(group);});
  const styles=$('#style-list');styles.replaceChildren();for(const s of [{id:null,name:'原有光色'},...project.styles]){const b=node('button',state.style?.id===s.id||!state.style&&!s.id?'active':'',s.name);b.type='button';b.addEventListener('click',()=>{ensureManual();manualDraft.style=s.id?{id:s.id,amount:Number($('#style-amount').value)||65}:null;$$('#style-list button').forEach(x=>x.classList.toggle('active',x===b));$('#style-amount').disabled=!manualDraft.style;$('#style-amount').value=manualDraft.style?.amount||0;$('#style-amount-value').value=$('#style-amount').value;$('#style-description').textContent=s.mood||'保留当前光色。';});styles.append(b);}$('#style-amount').disabled=!state.style;$('#style-amount').value=state.style?.amount||0;$('#style-amount-value').value=$('#style-amount').value;$('#style-description').textContent=project.styles.find(s=>s.id===state.style?.id)?.mood||'保留当前光色。';renderCrop(state.crop);controlledEdits?.renderActions();}
function renderCrop(crop=manualDraft?.crop||null){const root=$('#crop-fields');root.replaceChildren();for(const [key,label]of [['x','左'],['y','上'],['width','宽'],['height','高']]){const l=node('label','',label+' %'),input=node('input');input.type='number';input.min=0;input.max=100;input.step=.1;input.value=Number(((crop?.[key]??(['width','height'].includes(key)?1:0))*100).toFixed(1));input.dataset.crop=key;input.addEventListener('change',()=>{ensureManual();manualDraft.crop||={x:0,y:0,width:1,height:1};manualDraft.crop[key]=Number(input.value)/100;});l.append(input);root.append(l);}$('#crop-angle').value=crop?.angle||0;$('#crop-angle-value').value=(crop?.angle||0)+'°';controlledEdits?.renderActions();}
$('#style-amount').addEventListener('input',e=>{ensureManual();if(manualDraft.style)manualDraft.style.amount=Number(e.target.value);$('#style-amount-value').value=e.target.value;});$('#crop-angle').addEventListener('input',e=>{ensureManual();manualDraft.crop||={x:0,y:0,width:1,height:1};manualDraft.crop.angle=Number(e.target.value);$('#crop-angle-value').value=e.target.value+'°';});
for(const b of $$('[data-ratio]'))b.addEventListener('click',()=>{ensureManual();manualDraft.crop=b.dataset.ratio==='original'?null:ratioCrop(Number(b.dataset.ratio),project.source.width,project.source.height);$$('[data-ratio]').forEach(x=>x.classList.toggle('active',x===b));renderCrop();});
$('#trial-button').addEventListener('click',()=>perform(async()=>{if(noteDraft||intentDraft)throw Error('请先保存批注与意图，再生成试片。');ensureManual();if(!refinementSourceMatches(manualSource,project))throw Error('当前版本或所选组合已更新，请重置为所选版本后继续精调。');const state=manualDraft;const result=await json('candidate',{revision:project.revision,baseVersion:project.currentId,fromCandidate:manualSource.fromCandidate,name:$('#plan-name').value||'手动精调',settings:state.settings,style:state.style,crop:state.crop,goal:'按你的参数试片，保留当前版本供比较。',tradeoff:'请检查肤色、高光和局部过渡；更亮或更鲜艳不一定更适合。'});selectedCandidate=result.candidate.id;manualDraft=null;$('#adjustments').open=false;view='compare';zoom=null;pan={x:0,y:0};await refresh();notice('试片已准备好，接受前不会改变当前版本。');}));
$('#accept-button').addEventListener('click',()=>perform(async()=>{if(noteDraft||intentDraft||manualDraft||localDirty)throw Error('请先保存批注与意图，并试片或重置待调整参数，再接受这版。');const c=candidate();if(!selectedCandidateCanAccept(c,{pending:controlledEdits?.pending(),previewReady:previewReady&&previewGate.readyFor(previewIdentity())&&previewVersion===selectedCandidate&&view!=='original'&&view!=='photo'}))throw Error('请先选择调整，并查看与当前选择一致的完整预览。');await json('accept',{id:selectedCandidate,revision:project.revision,...(c.items?{selectionHash:c.selectionHash}:{})});selectedCandidate=null;view='current';manualDraft=null;localDraft=null;localDirty=false;await refresh();notice('已接受这版，原片和此前版本都可恢复。');}));
$('#discard-button').addEventListener('click',()=>perform(async()=>{await json('discard',{id:selectedCandidate,revision:project.revision});selectedCandidate=null;view='current';await refresh();notice('已取消试片，当前版本保持原来的效果。');}));
$('#note-text').addEventListener('input',()=>{noteDraft=true;renderActions();});$('#note-protect').addEventListener('change',()=>{noteDraft=true;renderActions();});$('#save-note').addEventListener('click',()=>perform(async()=>{await json('note',{id:selectedNote,note:$('#note-text').value,protect:$('#note-protect').checked,revision:project.revision});noteDraft=false;await refresh(false);notice('批注已保存。Agent 读取项目时会看到最新说明。');}));$('#delete-note').addEventListener('click',()=>perform(async()=>{await json('delete-note',{id:selectedNote,revision:project.revision});selectedNote=null;noteDraft=false;await refresh(false);notice('标记已删除。已接受的局部调整仍保留在版本中。');}));
async function saveIntent(){if(!intentDraft)return;if(busy||controlledEdits?.pending()){intentTimer=setTimeout(saveIntent,250);return;}const saved=await perform(async()=>{const value=$('#intent-input').value;await json('intent',{intent:value,revision:project.revision});if($('#intent-input').value===value)intentDraft=false;await refresh(false);$('#intent-status').textContent=intentDraft?'保存中…':'意图已保存';});$('#retry-intent').hidden=saved;if(!saved)$('#intent-status').textContent='意图尚未保存';else if(intentDraft)intentTimer=setTimeout(saveIntent,700);}
$('#retry-intent').addEventListener('click',saveIntent);
$('#intent-input').addEventListener('input',()=>{intentDraft=true;renderActions();clearTimeout(intentTimer);$('#intent-status').textContent='保存中…';intentTimer=setTimeout(saveIntent,600);});
async function copyContext(){if(noteDraft||intentDraft||manualDraft||localDirty||controlledEdits?.pending()){notice('先保存批注与意图，并试片或重置待调整参数，再复制给 Agent。');return;}const text=`用 $guangjian-retouch 继续精修这张照片。先读取项目的当前版本、最新意图与全部批注，再看实际预览，提出可以比较的候选。项目：${project.folder}\n意图：${project.intent||'保留原有表达'}\n当前版本：${project.currentId}\n正在看：${candidate()?`候选 ${candidate().id} · ${candidate().name}${candidate().stale?' · 已过期，请重新试片':' · 可用 fromCandidate 继续精调'}`:current().name}\n批注：${project.notes.map(n=>`${n.number}. ${n.note||'已圈选'}`).join('；')||'暂无'}`;try{await navigator.clipboard.writeText(text);notice('已复制。在当前 Agent 中粘贴即可继续。');}catch{notice('复制未成功，请让 Agent 读取当前项目，检查最新批注。');}}
$('#context-button').addEventListener('click',copyContext);$('#copy-project').addEventListener('click',copyContext);
$('#versions-button').addEventListener('click',()=>{$('#restore-error').hidden=true;const root=$('#version-list');root.replaceChildren();for(const v of [...project.versions].reverse()){const row=node('div','version-row'),copy=node('div');copy.append(node('strong','',v.name),node('small','',v.id===project.currentId?'当前版本':v.parentId?new Date(v.createdAt).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'保留最初画面'));const button=node('button','',v.id===project.currentId?'当前':'恢复');button.disabled=v.id===project.currentId;button.addEventListener('click',()=>perform(async()=>{if(noteDraft||intentDraft||manualDraft||localDirty)throw Error('请先保存批注和意图，试片或重置参数后再恢复版本。');await json('restore',{id:v.id,revision:project.revision});selectedCandidate=null;view='current';manualDraft=null;localDraft=null;$('#versions-dialog').close();await refresh();notice('版本已恢复。其他方案仍在版本列表中。');}));row.append(copy,button);root.append(row);}$('#versions-dialog').showModal();});
$('#export-button').addEventListener('click',()=>{exportFile=null;$('#export-result').hidden=true;$('#export-version').textContent='导出已保存版本：'+current().name;$('#export-text-label').hidden=!hasLetteringContent(current().state);$('#export-include-text').checked=view!=='photo';exportOptions.withoutText=view==='photo';$('#export-dialog').showModal();});
for(const b of $$('[data-export]'))b.addEventListener('click',()=>{exportOptions={preset:b.dataset.export,...({share:{format:'jpeg',maxSide:2048,quality:90},print:{format:'jpeg',maxSide:6000,quality:98},original:{format:'png',maxSide:8192,quality:98}}[b.dataset.export])};renderExport();});
function renderExport(){$$('[data-export]').forEach(b=>b.classList.toggle('active',b.dataset.export===exportOptions.preset));$$('[data-format]').forEach(b=>b.classList.toggle('active',b.dataset.format===exportOptions.format));$('#export-side').value=exportOptions.maxSide;$('#export-side-value').value=exportOptions.maxSide+' px';$('#export-quality').value=exportOptions.quality;$('#export-quality-value').value=exportOptions.quality;$('#export-quality').disabled=exportOptions.format==='png';}
for(const b of $$('[data-format]'))b.addEventListener('click',()=>{exportOptions.format=b.dataset.format;renderExport();});$('#export-side').addEventListener('input',e=>{exportOptions.maxSide=Number(e.target.value);$('#export-side-value').value=e.target.value+' px';});$('#export-quality').addEventListener('input',e=>{exportOptions.quality=Number(e.target.value);$('#export-quality-value').value=e.target.value;});
async function download(){const response=await api('download?file='+encodeURIComponent(exportFile.path.split('/').at(-1))),url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=exportFile.path.split('/').at(-1);document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export-confirm').addEventListener('click',()=>perform(async()=>{$('#export-confirm').textContent='正在生成成片…';try{exportFile=await json('export',{version:project.currentId,...exportOptions,withoutText:!$('#export-include-text').checked});const result=$('#export-result');result.replaceChildren(node('strong','',`成片已保存 · ${exportFile.width} × ${exportFile.height}`),node('p','quiet',exportFile.limited?'已按输出上限缩小；原片和编辑方案仍保留。':'已保存到项目的成片目录。'));const b=node('button','secondary','再次下载');b.addEventListener('click',()=>download().catch(e=>notice(e.message)));result.append(b);result.hidden=false;await download();await refresh(false);notice('成片已生成，下载已开始。');}finally{$('#export-confirm').textContent='生成并下载';}}));
$('#coordinate-note').addEventListener('click',()=>perform(async()=>{if(noteDraft||localDirty)throw Error('请先保存批注，试片或重置局部参数。');const rect=Object.fromEntries(['x','y','width','height'].map(key=>[key,Number($('#mark-'+key).value)/100]));const result=await json('note',{rect,note:'',revision:project.revision});selectedNote=result.note.id;view='original';fit();await refresh(false);await loadImages();$('#note-text').focus();notice('标记已添加，写下你的想法即可。');}));
$('#mark-button').addEventListener('click',()=>startMark());$('#add-note').addEventListener('click',()=>startMark());$('#draw-crop').addEventListener('click',()=>startMark('crop'));$('#help-button').addEventListener('click',()=>$('#help-dialog').showModal());for(const b of $$('[data-close]'))b.addEventListener('click',()=>b.closest('dialog').close());for(const d of $$('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
for(const b of $$('[data-view]'))b.addEventListener('click',()=>{endMark();view=b.dataset.view;fit();renderState();loadImages();});$('#fit-button').addEventListener('click',fit);$('#actual-button').addEventListener('click',()=>zoomTo(1));$('#zoom-in').addEventListener('click',()=>zoomTo(Math.min(4,(zoom??.5)*1.25)));$('#zoom-out').addEventListener('click',()=>zoomTo(Math.max(.08,(zoom??.5)/1.25)));$('#retry-image').addEventListener('click',async()=>{try{await refresh(false);await loadImages(zoom>=1);}catch(e){$('#preview-error-message').textContent=e.message;$('#preview-error').hidden=false;}});
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA/.test(e.target.tagName)||$('dialog[open]'))return;if(e.key==='Escape'){endMark();return;}if(e.key==='0'){e.preventDefault();fit();}if(e.key==='1'){e.preventDefault();zoomTo(1);}if(e.key==='+'||e.key==='=')$('#zoom-in').click();if(e.key==='-')$('#zoom-out').click();if(e.key.toLowerCase()==='m')startMark();});
document.addEventListener('input',event=>{if(event.target.closest('#adjustments,#local-controls,#lettering-dialog'))renderActions();});
window.addEventListener('resize',()=>{positionImages();});window.addEventListener('beforeunload',e=>{if(noteDraft||intentDraft||manualDraft||localDirty||letteringEditor?.dirty()||controlledEdits?.pending()||controlledEdits?.dirty()){e.preventDefault();e.returnValue='';}});
for(const control of $$('#versions-button,#mark-button,#add-note,#export-button,#coordinate-note,#context-button,#copy-project,#intent-input,#lettering-open,#trial-button,#local-trial,[data-view]'))control.disabled=true;
controlledEdits=createControlledEdits({getContext:()=>({project,current:project?current():null,candidate:project?candidate():null,view,busy,previewReady,selectedNote,dirty:noteDraft||intentDraft||Boolean(manualDraft)||localDirty||Boolean(letteringEditor?.dirty()),annotationDirty:noteDraft||intentDraft||Boolean(manualDraft)||localDirty||Boolean(letteringEditor?.dirty())}),json,perform,notice,invalidatePreview,applyProject,render:renderState,reloadImages:loadImages,refreshProject:refresh,labels,showAccepted:async()=>{if(manualDraft||localDirty){notice('请先试片或重置待调整参数，再查看已保存画面。');return;}endMark();selectedCandidate=null;view='current';zoom=null;pan={x:0,y:0};invalidatePreview();renderState();await loadImages();},showCandidate:async id=>{endMark();selectedCandidate=id;view=candidate()?.guardOperation?'current':'compare';zoom=null;pan={x:0,y:0};invalidatePreview();renderState();await loadImages();},startProtection:()=>startMark('protect')});
letteringEditor=createLetteringEditor({getProject:()=>project,getBase:()=>showing(),json,perform,notice,canStart:()=>{if(candidate()?.stale){notice('这份试片已过期，请重新试片后再添加文字。');return false;}if(candidate()?.guardOperation){notice('请先接受或取消解除保护试片，再添加文字。');return false;}if(noteDraft||intentDraft||manualDraft||localDirty){notice('先保存批注与意图，并试片或重置待调整参数，再进入文字模式。');return false;}return true;},onTrial:async id=>{selectedCandidate=id;view='compare';zoom=null;pan={x:0,y:0};await refresh();}});
await refresh().catch(e=>{notice(e.message);$('#save-state').textContent='连接未就绪';$('#image-empty').hidden=false;$('#preview-error-message').textContent=e.message;$('#preview-error').hidden=false;});
const projectPoller=createProjectPoller({
  read:()=>json('project'),getProject:()=>project,
  blocked:()=>busy||controlledEdits?.pending()||noteDraft||intentDraft||markMode||document.hidden||document.activeElement?.matches('input,textarea')||Boolean($('dialog[open]')),
  async update(next,previous){
    const oldId=previous?.currentId;chooseNewCandidate(previous,next);applyProject(next);renderState();
    if(oldId!==project.currentId){zoom=null;pan={x:0,y:0};}
    await loadImages();
  },
  connected:renderSaveState,
  onError(){const state=$('#save-state');state.textContent=project?'连接中断 · 编辑已保存':'连接未就绪';state.classList.add('warning');},
});
projectPoller.start();
window.addEventListener('pagehide',()=>projectPoller.stop());
window.addEventListener('pageshow',()=>projectPoller.start());

async function renderEditSources(){
  const version=showing()?.id;if(!version)return;const root=$('#edit-sources-content');root.textContent='正在读取调整来源…';
  try{const sources=await json('edit-sources?version='+encodeURIComponent(version));if(showing()?.id!==version)return;root.replaceChildren();
    for(const p of sources.parameters.filter(p=>p.manual||p.styleContribution)){const row=node('div','source-row');row.append(node('strong','',labels[p.key]||p.key),node('span','quiet',`手动 ${p.manual} · 风格 ${Number(p.styleContribution.toFixed(2))} → ${Number(p.effective.toFixed(2))}`));root.append(row);}
    for(const l of sources.locals){const row=node('div','source-row');row.append(node('strong','','局部 · '+(l.note||'画面范围')),node('span','quiet',(l.enabled===false?'已暂停':'已启用')+' · '+Object.keys(l.settings).filter(k=>l.settings[k]).map(k=>(labels[k]||k)+' '+l.settings[k]).join('，')));root.append(row);}
    if(!root.children.length)root.textContent='当前没有光色调整；原片关系保持。';
  }catch(e){if(showing()?.id===version)root.textContent=e.message;}
}
$('#edit-sources-section').addEventListener('toggle',()=>{if($('#edit-sources-section').open)renderEditSources();});
