import {ratioCrop,transformRect,originalToViewPoint} from '/engine/photo-geometry.js';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)],token=new URLSearchParams(location.hash.slice(1)).get('token')||sessionStorage.getItem('guangjian-local-session');
if(token)sessionStorage.setItem('guangjian-local-session',token);history.replaceState(null,'',location.pathname);
let project,selectedCandidate=null,selectedNote=null,view='current',markMode=null,drag=null,zoom=null,pan={x:0,y:0},loadGeneration=0,imageURLs=[],noteDraft=false,localDraft=null,localDirty=false,previewVersion=null,previewReady=false,intentDraft=false,manualDraft=null,manualBase=null,exportOptions={preset:'share',format:'jpeg',maxSide:2048,quality:90},exportFile=null,intentTimer,noticeTimer,busy=false;
const labels={exposure:'曝光',contrast:'对比度',highlights:'高光',shadows:'阴影',whites:'白色色阶',blacks:'黑色色阶',warmth:'色温倾向',tint:'色调',vibrance:'自然饱和度',saturation:'饱和度',curveShadows:'曲线 · 暗部',curveMidtones:'曲线 · 中间调',curveHighlights:'曲线 · 亮部',orangeHue:'橙色 · 色相',orangeSaturation:'橙色 · 饱和度',orangeLuminance:'橙色 · 明度',greenHue:'绿色 · 色相',greenSaturation:'绿色 · 饱和度',greenLuminance:'绿色 · 明度',blueHue:'蓝色 · 色相',blueSaturation:'蓝色 · 饱和度',blueLuminance:'蓝色 · 明度',texture:'纹理',clarity:'清晰度',dehaze:'去朦胧',sharpen:'锐化',denoise:'降噪',fade:'褪色',vignette:'暗角',grain:'颗粒',monochrome:'黑白强度'};
const current=()=>project.versions.find(v=>v.id===project.currentId),candidate=()=>project.candidates.find(c=>c.id===selectedCandidate),note=()=>project.notes.find(n=>n.id===selectedNote),showing=()=>candidate()||current();
function notice(message){$('#notice').textContent=message;$('#notice').hidden=false;clearTimeout(noticeTimer);noticeTimer=setTimeout(()=>$('#notice').hidden=true,5500);}
async function api(route,data){const response=await fetch('/api/'+route,{method:data?'POST':'GET',headers:{'X-Guangjian-Token':token||'',...(data?{'Content-Type':'application/json'}:{})},...(data?{body:JSON.stringify(data)}:{})});if(!response.ok){let value;try{value=await response.json();}catch{}throw Error(value?.error?.message||'连接暂时中断，请保留当前页面并重新连接。');}return response;}
async function json(route,data){return (await api(route,data)).json();}
async function perform(fn){if(busy)return;busy=true;renderActions();let success=false;try{await fn();success=true;}catch(error){notice(error.message);await refresh(false).catch(()=>{});}finally{busy=false;renderActions();}return success;}
function chooseNewCandidate(old,next){if(selectedCandidate&&!next.candidates.some(c=>c.id===selectedCandidate))selectedCandidate=null;const added=next.candidates.filter(c=>!c.stale&&!old?.candidates.some(x=>x.id===c.id));if(added.length)selectedCandidate=added.at(-1).id;}
async function refresh(images=true){const next=await json('project');const old=project,changed=!old||old.currentId!==next.currentId||old.candidates.length!==next.candidates.length;chooseNewCandidate(old,next);project=next;renderState();if(images&&(changed||!old))await loadImages();}
function node(tag,className,text){const e=document.createElement(tag);if(className)e.className=className;if(text!==undefined)e.textContent=text;return e;}
function renderState(){
  $('#photo-name').textContent=project.source.name;$('#photo-name').title=project.source.name;$('#save-state').textContent=project.exports.some(e=>e.versionId===project.currentId)?'已导出 · 草稿已保存':project.acceptedId===project.currentId?'已接受 · 草稿已保存':'草稿已保存';
  if(!intentDraft&&document.activeElement!==$('#intent-input'))$('#intent-input').value=project.intent;
  const list=$('#candidate-list');list.replaceChildren();for(const c of project.candidates){const b=node('button',c.id===selectedCandidate?'active':'',c.name);b.type='button';b.dataset.candidate=c.id;b.setAttribute('aria-pressed',String(c.id===selectedCandidate));b.addEventListener('click',()=>{selectedCandidate=c.id;renderState();view='compare';zoom=null;pan={x:0,y:0};loadImages();});list.append(b);}
  $('#candidate-section').hidden=!project.candidates.length;$('#candidate-count').textContent=project.candidates.length+' 个方向';
  const c=candidate();if(c){$('#candidate-name').textContent=c.name;$('#candidate-goal').textContent=c.goal||'比较当前版本与这份候选，选择更符合意图的一版。';$('#candidate-caution').textContent=[c.tradeoff,...c.warnings].filter(Boolean).join('\n')||'留意高光、肤色和局部边缘是否仍然自然。';$('#candidate-stale').hidden=!c.stale;}
  $('#next-step').textContent=c?(c.stale?'意图或批注已更新，请重新试片。':'先看完整构图，再放大检查细节。'):project.versions.length>1?'这版已保存。可以导出，也可以继续精调。':'先在 Agent 中审片，也可以从一次轻调开始。';
  const review=project.reviews.at(-1);$('#review-section').hidden=!review;if(review){$('#review-summary').textContent=review.summary;$('#review-preserve').replaceChildren(...review.preserve.map(x=>node('li','',x)));}
  renderNotes();renderActions();$$('[data-view]').forEach(b=>{b.hidden=b.dataset.view==='compare'&&project.versions.length===1&&!c;b.classList.toggle('active',b.dataset.view===view);b.setAttribute('aria-pressed',String(b.dataset.view===view));});
  if(!manualDraft)resetManual();
}
function renderActions(){if(!project)return;for(const button of $$('#context-button,#copy-project,#intent-input,[data-view]'))button.disabled=false;for(const button of $$('#save-note,#delete-note,#local-trial,#mark-button,#add-note,#draw-crop,#versions-button,#coordinate-note'))button.disabled=busy;const c=candidate();$('#candidate-actions').hidden=!c;$('#accept-button').disabled=busy||!c||c.stale||!previewReady||previewVersion!==c.id||noteDraft||intentDraft;$('#accept-button').title=!previewReady||previewVersion!==c?.id?'先查看这份试片的实际效果':'';$('#manual-stale').hidden=!manualDraft||manualBase===project.currentId;$('#discard-button').disabled=busy;$('#trial-button').disabled=busy;$('#export-confirm').disabled=busy;$('#export-button').classList.toggle('primary',!c&&project.versions.length>1);$('#export-button').disabled=busy||Boolean(c);$('#export-button').title=c?'先接受或取消试片，再导出已保存版本':'';}
function renderNotes(){const list=$('#note-list');list.replaceChildren();$('#notes-empty').hidden=project.notes.length>0;$('#note-count').textContent=project.notes.length?String(project.notes.length):'';if(!project.notes.some(n=>n.id===selectedNote)){selectedNote=null;noteDraft=false;}
  for(const n of project.notes){const b=node('button','note-item'+(n.id===selectedNote?' active':''));b.type='button';b.dataset.note=n.id;b.append(node('b','',String(n.number)),node('span','',n.note||'已圈选，写一句你的想法'));b.addEventListener('click',()=>{if((noteDraft||localDirty)&&selectedNote!==n.id){notice('请先保存批注，或试片／重置局部参数后再切换标记。');return;}selectedNote=n.id;renderNotes();drawMarks();$('#note-text').focus();});b.addEventListener('pointerenter',()=>drawMarks(n.id));b.addEventListener('pointerleave',()=>drawMarks());list.append(b);}
  const n=note();$('#note-editor').hidden=!n;if(n){$('#note-label').textContent=`标记 ${n.number} · 你的想法`;if(!noteDraft){$('#note-text').value=n.note;$('#note-protect').checked=n.protect;}if(localDraft?.id!==n.id||localDraft.base!==project.currentId&&!localDirty)buildLocal(n);}drawMarks();}
function buildLocal(n){const saved=current().state.locals.find(l=>l.id===n.id);localDirty=false;localDraft={id:n.id,base:project.currentId,settings:{...saved?.localSettings},feather:saved?.feather??.36,maskType:saved?.maskType||'rectangle'};const root=$('#local-parameters');root.replaceChildren();for(const key of ['exposure','shadows','warmth']){const range=project.parameters.find(p=>p.key===key).range,label=node('label','slider-label',labels[key]),out=node('output','',localDraft.settings[key]||0),input=node('input');label.htmlFor='local-'+key;input.id=label.htmlFor;input.type='range';input.min=range[0];input.max=range[1];input.step=key==='exposure'?.01:1;input.value=localDraft.settings[key]||0;input.addEventListener('input',()=>{localDirty=true;localDraft.settings[key]=Number(input.value);out.value=input.value;});label.append(out);root.append(label,input);}$('#local-feather').value=localDraft.feather*100;$('#local-feather-value').value=Math.round(localDraft.feather*100)+'%';$$('[data-mask]').forEach(b=>b.classList.toggle('active',b.dataset.mask===localDraft.maskType));}
$('#local-feather').addEventListener('input',e=>{localDirty=true;localDraft.feather=Number(e.target.value)/100;$('#local-feather-value').value=e.target.value+'%';});for(const b of $$('[data-mask]'))b.addEventListener('click',()=>{localDirty=true;localDraft.maskType=b.dataset.mask;$$('[data-mask]').forEach(x=>x.classList.toggle('active',x===b));});
$('#local-reset').addEventListener('click',()=>{buildLocal(note());notice('已读取这处当前版本的参数。');});
$('#local-trial').addEventListener('click',()=>perform(async()=>{if(noteDraft||intentDraft)throw Error('请先保存批注与意图，再生成局部试片。');if(localDraft.base!==project.currentId)throw Error('当前版本已更新，请读取当前局部参数后再精调。');const result=await json('candidate',{revision:project.revision,baseVersion:project.currentId,name:`标记 ${note().number} · 局部版`,locals:[{annotationId:selectedNote,settings:localDraft.settings,feather:localDraft.feather,maskType:localDraft.maskType}],goal:'只调整这处范围，保留其他已接受的效果。',tradeoff:'几何范围可能包含背景，请放大检查过渡。'});selectedCandidate=result.candidate.id;localDirty=false;view='compare';zoom=null;pan={x:0,y:0};await refresh();await loadImages();notice('局部试片已准备好，检查边缘后再接受。');}));
function drawMarks(active=selectedNote){const layer=$('#mark-layer');layer.replaceChildren();if(!project||view==='compare'||markMode==='crop')return;const image=$('#image-b'),pane=$('#pane-b'),crop=view==='original'?null:showing().state.crop;if(!image.naturalWidth)return;const r=image.getBoundingClientRect(),box=pane.getBoundingClientRect();for(const n of project.notes){const rect=crop?transformRect(n.rect,p=>originalToViewPoint(p,crop,project.source.width,project.source.height)):n.rect;if(!rect)continue;const el=node('div','mark-box'+(n.id===active?' active':''));el.style.cssText=`left:${r.left-box.left+rect.x*r.width}px;top:${r.top-box.top+rect.y*r.height}px;width:${rect.width*r.width}px;height:${rect.height*r.height}px`;el.append(node('span','',n.number));layer.append(el);}}
async function imageURL(version,{size=1400,reference}={}){const route=`image?version=${encodeURIComponent(version)}&size=${size}${reference?'&reference='+encodeURIComponent(reference):''}`,response=await api(route);const blob=await response.blob();return {url:URL.createObjectURL(blob),limited:response.headers.get('X-Photo-Limited')==='true'};}
function decodeImage(url){return new Promise((resolve,reject)=>{const image=new Image();image.onload=()=>resolve(image);image.onerror=reject;image.src=url;});}
async function loadImages(full=false){if(!project)return;const generation=++loadGeneration,c=candidate(),selected=showing(),key=view==='original'?'original':selected.id,size=full?8192:1400;previewReady=false;renderActions();$('#image-loading').hidden=false;$('#image-empty').hidden=true;
  try{const pair=await Promise.all([imageURL(key,{size}),view==='compare'?imageURL(c?project.currentId:'original',{size,reference:selected.id}):null]);await Promise.all(pair.filter(Boolean).map(x=>decodeImage(x.url)));
    if(generation!==loadGeneration){pair.filter(Boolean).forEach(x=>URL.revokeObjectURL(x.url));return;}
    imageURLs.forEach(URL.revokeObjectURL);imageURLs=pair.filter(Boolean).map(x=>x.url);$('#image-b').src=pair[0].url;if(pair[1])$('#image-a').src=pair[1].url;$('#pane-a').hidden=view!=='compare';$('#photo-panes').classList.toggle('compare',view==='compare');$('#pane-a .photo-tag').textContent=c?'当前 · 相同范围':'原片 · 相同范围';$('#photo-tag').textContent=view==='original'?'原片':c?'试看片 · 尚未接受':current().name;
    $('#image-size').textContent=`${project.source.width} × ${project.source.height}`;$('#view-caption').textContent=view==='compare'?'共享位置与倍率':'完整构图';previewVersion=key;previewReady=true;
    await new Promise(requestAnimationFrame);positionImages();drawMarks();if(full&&pair.some(x=>x?.limited))notice('照片超过输出尺寸上限，当前细节预览已缩小。请让 Agent 用区域预览检查原片细节。');
  }catch(error){if(generation===loadGeneration){$('#image-empty').hidden=true;notice(error.message);if(!$('#image-b').src)$('#image-empty').hidden=false;}}
  finally{if(generation===loadGeneration){$('#image-loading').hidden=true;renderActions();}}
}
function positionImages(){const visible=$$('.pane').filter(x=>!x.hidden),image=$('#image-b');if(!image.naturalWidth)return;const fit=Math.min(...visible.map(p=>Math.min(p.clientWidth/image.naturalWidth,p.clientHeight/image.naturalHeight)))*.95,z=zoom??fit;
  for(const p of visible){const img=p.querySelector('img');img.style.width=img.naturalWidth*z+'px';img.style.height=img.naturalHeight*z+'px';img.style.left=(p.clientWidth-img.naturalWidth*z)/2+pan.x+'px';img.style.top=(p.clientHeight-img.naturalHeight*z)/2+pan.y+'px';}
  $('#zoom-label').textContent=zoom===null?'适应':Math.round(z*100)+'%';$('#fit-button').classList.toggle('active',zoom===null);$('#actual-button').classList.toggle('active',zoom===1);drawMarks();}
async function zoomTo(value){if(!project)return;if(value===1||value>1)await loadImages(true);zoom=value;pan={x:0,y:0};positionImages();}
function fit(){zoom=null;pan={x:0,y:0};positionImages();}
function relativePoint(event){const r=$('#image-b').getBoundingClientRect();return {x:Math.max(0,Math.min(1,(event.clientX-r.left)/r.width)),y:Math.max(0,Math.min(1,(event.clientY-r.top)/r.height))};}
async function startMark(mode='note'){if(noteDraft){notice('请先保存当前批注。');return;}markMode=mode;view='original';fit();renderState();await loadImages();$('#photo-stage').classList.add('marking');$('#mark-hint').hidden=false;$('#mark-hint').textContent=mode==='crop'?'在原片上框选想保留的范围 · Esc 取消':'框选想讨论的地方，完成后写一句你的想法 · Esc 取消';}
function endMark(){markMode=null;$('#photo-stage').classList.remove('marking');$('#mark-hint').hidden=true;$('#draft-rect').hidden=true;}
$('#pane-b').addEventListener('pointerdown',e=>{if(e.button!==0||!previewReady)return;if(markMode){const r=$('#image-b').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)return;drag={kind:markMode,start:relativePoint(e)};}else drag={kind:'pan',x:e.clientX,y:e.clientY,pan:{...pan}};$('#pane-b').setPointerCapture(e.pointerId);});
$('#pane-b').addEventListener('pointermove',e=>{if(!drag||!$('#pane-b').hasPointerCapture(e.pointerId))return;if(drag.kind==='pan'){pan={x:drag.pan.x+e.clientX-drag.x,y:drag.pan.y+e.clientY-drag.y};positionImages();return;}const p=relativePoint(e),s=drag.start;drag.rect={x:Math.min(s.x,p.x),y:Math.min(s.y,p.y),width:Math.abs(p.x-s.x),height:Math.abs(p.y-s.y)};const r=$('#image-b').getBoundingClientRect(),b=$('#pane-b').getBoundingClientRect();$('#draft-rect').hidden=false;$('#draft-rect').style.cssText=`left:${r.left-b.left+drag.rect.x*r.width}px;top:${r.top-b.top+drag.rect.y*r.height}px;width:${drag.rect.width*r.width}px;height:${drag.rect.height*r.height}px`;});
$('#pane-b').addEventListener('pointerup',e=>{if(!drag)return;const d=drag;drag=null;if(d.kind==='pan')return;if(!d.rect||d.rect.width<.01||d.rect.height<.01){notice('范围太小，请再框选一次。');return;}const mode=markMode;endMark();if(mode==='crop'){ensureManual();manualDraft.crop=d.rect;renderCrop();$('#adjustments').open=true;notice('裁剪范围已选好，生成试片即可检查。');}else perform(async()=>{const result=await json('note',{rect:d.rect,note:'',revision:project.revision});selectedNote=result.note.id;await refresh(false);$('#note-editor').scrollIntoView({block:'nearest',behavior:'smooth'});$('#note-text').focus();});});
$('#pane-b').addEventListener('pointercancel',()=>{drag=null;$('#draft-rect').hidden=true;});
$('#pane-a').addEventListener('pointerdown',e=>{if(e.button!==0)return;drag={kind:'pan-a',x:e.clientX,y:e.clientY,pan:{...pan}};e.currentTarget.setPointerCapture(e.pointerId);});$('#pane-a').addEventListener('pointermove',e=>{if(drag?.kind!=='pan-a'||!e.currentTarget.hasPointerCapture(e.pointerId))return;pan={x:drag.pan.x+e.clientX-drag.x,y:drag.pan.y+e.clientY-drag.y};positionImages();});for(const type of ['pointerup','pointercancel'])$('#pane-a').addEventListener(type,()=>drag=null);
for(const p of $$('.pane')){p.addEventListener('wheel',e=>{if(markMode)return;e.preventDefault();const image=$('#image-b'),base=zoom??Math.min(p.clientWidth/image.naturalWidth,p.clientHeight/image.naturalHeight)*.95;zoom=Math.min(4,Math.max(.08,base*Math.exp(-e.deltaY*.002)));positionImages();},{passive:false});p.addEventListener('keydown',e=>{const d={ArrowLeft:[-32,0],ArrowRight:[32,0],ArrowUp:[0,-32],ArrowDown:[0,32]}[e.key];if(d){e.preventDefault();pan={x:pan.x+d[0],y:pan.y+d[1]};positionImages();}});}
function ensureManual(){if(!manualDraft){manualDraft=structuredClone(current().state);manualBase=project.currentId;}}
function resetManual(){manualDraft=null;manualBase=null;buildAdjustments(current().state);}
$('#manual-reset').addEventListener('click',()=>{resetManual();renderActions();notice('已读取当前版本参数，未试片的手动输入已重置。');});
function buildAdjustments(state){const groups=[['光线与色彩',['exposure','highlights','shadows','contrast','whites','blacks','warmth','tint','vibrance','saturation']],['细节与质感',['texture','clarity','dehaze','sharpen','denoise','fade','grain','vignette','monochrome']],['曲线与分色',['curveShadows','curveMidtones','curveHighlights','orangeHue','orangeSaturation','orangeLuminance','greenHue','greenSaturation','greenLuminance','blueHue','blueSaturation','blueLuminance']]];const root=$('#adjustment-groups');root.replaceChildren();groups.forEach(([title,keys],i)=>{const group=node('details','parameter-group');group.open=i===0;group.append(node('summary','',title));for(const key of keys){const info=project.parameters.find(x=>x.key===key),label=node('label','slider-label',labels[key]);label.htmlFor='parameter-'+key;const out=node('output','',String(state.settings[key]??0));label.append(out);const input=node('input');input.id='parameter-'+key;input.type='range';input.min=info.range[0];input.max=info.range[1];input.step=key==='exposure'?.01:1;input.value=state.settings[key]??0;input.dataset.parameter=key;input.addEventListener('input',()=>{ensureManual();manualDraft.settings[key]=Number(input.value);out.value=input.value;});group.append(label,input);}root.append(group);});
  const styles=$('#style-list');styles.replaceChildren();for(const s of [{id:null,name:'原有光色'},...project.styles]){const b=node('button',state.style?.id===s.id||!state.style&&!s.id?'active':'',s.name);b.type='button';b.addEventListener('click',()=>{ensureManual();manualDraft.style=s.id?{id:s.id,amount:Number($('#style-amount').value)||65}:null;$$('#style-list button').forEach(x=>x.classList.toggle('active',x===b));$('#style-amount').value=manualDraft.style?.amount||0;$('#style-amount-value').value=$('#style-amount').value;$('#style-description').textContent=s.mood||'保留当前光色。';});styles.append(b);}$('#style-amount').value=state.style?.amount||0;$('#style-amount-value').value=$('#style-amount').value;$('#style-description').textContent=project.styles.find(s=>s.id===state.style?.id)?.mood||'保留当前光色。';renderCrop(state.crop);}
function renderCrop(crop=manualDraft?.crop||null){const root=$('#crop-fields');root.replaceChildren();for(const [key,label]of [['x','左'],['y','上'],['width','宽'],['height','高']]){const l=node('label','',label+' %'),input=node('input');input.type='number';input.min=0;input.max=100;input.step=.1;input.value=Number(((crop?.[key]??(['width','height'].includes(key)?1:0))*100).toFixed(1));input.dataset.crop=key;input.addEventListener('change',()=>{ensureManual();manualDraft.crop||={x:0,y:0,width:1,height:1};manualDraft.crop[key]=Number(input.value)/100;});l.append(input);root.append(l);}$('#crop-angle').value=crop?.angle||0;$('#crop-angle-value').value=(crop?.angle||0)+'°';}
$('#style-amount').addEventListener('input',e=>{ensureManual();if(manualDraft.style)manualDraft.style.amount=Number(e.target.value);$('#style-amount-value').value=e.target.value;});$('#crop-angle').addEventListener('input',e=>{ensureManual();manualDraft.crop||={x:0,y:0,width:1,height:1};manualDraft.crop.angle=Number(e.target.value);$('#crop-angle-value').value=e.target.value+'°';});
for(const b of $$('[data-ratio]'))b.addEventListener('click',()=>{ensureManual();manualDraft.crop=b.dataset.ratio==='original'?null:ratioCrop(Number(b.dataset.ratio),project.source.width,project.source.height);$$('[data-ratio]').forEach(x=>x.classList.toggle('active',x===b));renderCrop();});
$('#trial-button').addEventListener('click',()=>perform(async()=>{if(noteDraft||intentDraft)throw Error('请先保存批注与意图，再生成试片。');ensureManual();if(manualBase!==project.currentId)throw Error('Agent 已更新当前版本。请点击「读取当前参数」后继续精调。');const state=manualDraft;const result=await json('candidate',{revision:project.revision,baseVersion:project.currentId,name:$('#plan-name').value||'手动精调',settings:state.settings,style:state.style,crop:state.crop,goal:'按你的参数试片，保留当前版本供比较。',tradeoff:'请检查肤色、高光和局部过渡；更亮或更鲜艳不一定更适合。'});selectedCandidate=result.candidate.id;manualDraft=null;$('#adjustments').open=false;view='compare';zoom=null;pan={x:0,y:0};await refresh();await loadImages();notice('试片已准备好，接受前不会改变当前版本。');}));
$('#accept-button').addEventListener('click',()=>perform(async()=>{if(noteDraft||intentDraft)throw Error('请先保存批注与意图，再接受这版。');if(!previewReady||previewVersion!==selectedCandidate)throw Error('请先查看这份候选的实际预览。');await json('accept',{id:selectedCandidate,revision:project.revision});selectedCandidate=null;view='current';manualDraft=null;localDraft=null;localDirty=false;await refresh();await loadImages();notice('已接受这版，原片和此前版本都可恢复。');}));
$('#discard-button').addEventListener('click',()=>perform(async()=>{await json('discard',{id:selectedCandidate,revision:project.revision});selectedCandidate=null;view='current';await refresh();await loadImages();notice('已取消试片，当前版本保持原来的效果。');}));
$('#note-text').addEventListener('input',()=>{noteDraft=true;renderActions();});$('#note-protect').addEventListener('change',()=>{noteDraft=true;renderActions();});$('#save-note').addEventListener('click',()=>perform(async()=>{await json('note',{id:selectedNote,note:$('#note-text').value,protect:$('#note-protect').checked,revision:project.revision});noteDraft=false;await refresh(false);notice('批注已保存。Agent 读取项目时会看到最新说明。');}));$('#delete-note').addEventListener('click',()=>perform(async()=>{await json('delete-note',{id:selectedNote,revision:project.revision});selectedNote=null;noteDraft=false;await refresh(false);notice('标记已删除。已接受的局部调整仍保留在版本中。');}));
async function saveIntent(){if(!intentDraft)return;if(busy){intentTimer=setTimeout(saveIntent,250);return;}const saved=await perform(async()=>{const value=$('#intent-input').value;await json('intent',{intent:value,revision:project.revision});if($('#intent-input').value===value)intentDraft=false;await refresh(false);$('#intent-status').textContent=intentDraft?'保存中…':'意图已保存';});$('#retry-intent').hidden=saved;if(!saved)$('#intent-status').textContent='意图尚未保存';else if(intentDraft)intentTimer=setTimeout(saveIntent,700);}
$('#retry-intent').addEventListener('click',saveIntent);
$('#intent-input').addEventListener('input',()=>{intentDraft=true;renderActions();clearTimeout(intentTimer);$('#intent-status').textContent='保存中…';intentTimer=setTimeout(saveIntent,600);});
async function copyContext(){const text=`用 $guangjian-retouch 继续精修这张照片。先读取项目的当前版本、最新意图与全部批注，再看实际预览，提出可以比较的候选。项目：${project.folder}\n意图：${project.intent||'保留原有表达'}\n当前版本：${project.currentId}\n批注：${project.notes.map(n=>`${n.number}. ${n.note||'已圈选'}`).join('；')||'暂无'}`;try{await navigator.clipboard.writeText(text);notice('已复制。在当前 Agent 中粘贴即可继续。');}catch{notice('复制未成功，请让 Agent 读取当前项目，检查最新批注。');}}
$('#context-button').addEventListener('click',copyContext);$('#copy-project').addEventListener('click',copyContext);
$('#versions-button').addEventListener('click',()=>{const root=$('#version-list');root.replaceChildren();for(const v of [...project.versions].reverse()){const row=node('div','version-row'),copy=node('div');copy.append(node('strong','',v.name),node('small','',v.id===project.currentId?'当前版本':v.parentId?new Date(v.createdAt).toLocaleString('zh-CN',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'保留最初画面'));const button=node('button','',v.id===project.currentId?'当前':'恢复');button.disabled=v.id===project.currentId;button.addEventListener('click',()=>perform(async()=>{if(noteDraft||intentDraft||manualDraft||localDirty)throw Error('请先保存批注和意图，试片或重置参数后再恢复版本。');await json('restore',{id:v.id,revision:project.revision});selectedCandidate=null;view='current';manualDraft=null;localDraft=null;$('#versions-dialog').close();await refresh();await loadImages();notice('版本已恢复。其他方案仍在版本列表中。');}));row.append(copy,button);root.append(row);}$('#versions-dialog').showModal();});
$('#export-button').addEventListener('click',()=>{exportFile=null;$('#export-result').hidden=true;$('#export-version').textContent='导出已保存版本：'+current().name;$('#export-dialog').showModal();});
for(const b of $$('[data-export]'))b.addEventListener('click',()=>{exportOptions={preset:b.dataset.export,...({share:{format:'jpeg',maxSide:2048,quality:90},print:{format:'jpeg',maxSide:6000,quality:98},original:{format:'png',maxSide:8192,quality:98}}[b.dataset.export])};renderExport();});
function renderExport(){$$('[data-export]').forEach(b=>b.classList.toggle('active',b.dataset.export===exportOptions.preset));$$('[data-format]').forEach(b=>b.classList.toggle('active',b.dataset.format===exportOptions.format));$('#export-side').value=exportOptions.maxSide;$('#export-side-value').value=exportOptions.maxSide+' px';$('#export-quality').value=exportOptions.quality;$('#export-quality-value').value=exportOptions.quality;$('#export-quality').disabled=exportOptions.format==='png';}
for(const b of $$('[data-format]'))b.addEventListener('click',()=>{exportOptions.format=b.dataset.format;renderExport();});$('#export-side').addEventListener('input',e=>{exportOptions.maxSide=Number(e.target.value);$('#export-side-value').value=e.target.value+' px';});$('#export-quality').addEventListener('input',e=>{exportOptions.quality=Number(e.target.value);$('#export-quality-value').value=e.target.value;});
async function download(){const response=await api('download?file='+encodeURIComponent(exportFile.path.split('/').at(-1))),url=URL.createObjectURL(await response.blob()),a=document.createElement('a');a.href=url;a.download=exportFile.path.split('/').at(-1);document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
$('#export-confirm').addEventListener('click',()=>perform(async()=>{$('#export-confirm').textContent='正在生成成片…';try{exportFile=await json('export',{version:project.currentId,...exportOptions});const result=$('#export-result');result.replaceChildren(node('strong','',`成片已保存 · ${exportFile.width} × ${exportFile.height}`),node('p','quiet',exportFile.limited?'已按输出上限缩小；原片和编辑方案仍保留。':'已保存到项目的成片目录。'));const b=node('button','secondary','再次下载');b.addEventListener('click',()=>download().catch(e=>notice(e.message)));result.append(b);result.hidden=false;await download();await refresh(false);notice('成片已生成，下载已开始。');}finally{$('#export-confirm').textContent='生成并下载';}}));
$('#coordinate-note').addEventListener('click',()=>perform(async()=>{if(noteDraft||localDirty)throw Error('请先保存批注，试片或重置局部参数。');const rect=Object.fromEntries(['x','y','width','height'].map(key=>[key,Number($('#mark-'+key).value)/100]));const result=await json('note',{rect,note:'',revision:project.revision});selectedNote=result.note.id;view='original';fit();await refresh(false);await loadImages();$('#note-text').focus();notice('标记已添加，写下你的想法即可。');}));
$('#mark-button').addEventListener('click',()=>startMark());$('#add-note').addEventListener('click',()=>startMark());$('#draw-crop').addEventListener('click',()=>startMark('crop'));$('#help-button').addEventListener('click',()=>$('#help-dialog').showModal());for(const b of $$('[data-close]'))b.addEventListener('click',()=>b.closest('dialog').close());for(const d of $$('dialog'))d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});
for(const b of $$('[data-view]'))b.addEventListener('click',()=>{endMark();view=b.dataset.view;fit();renderState();loadImages();});$('#fit-button').addEventListener('click',fit);$('#actual-button').addEventListener('click',()=>zoomTo(1));$('#zoom-in').addEventListener('click',()=>zoomTo(Math.min(4,(zoom??.5)*1.25)));$('#zoom-out').addEventListener('click',()=>zoomTo(Math.max(.08,(zoom??.5)/1.25)));$('#retry-image').addEventListener('click',()=>refresh().catch(e=>notice(e.message)));
document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA/.test(e.target.tagName)||$('dialog[open]'))return;if(e.key==='Escape'){endMark();return;}if(e.key==='0'){e.preventDefault();fit();}if(e.key==='1'){e.preventDefault();zoomTo(1);}if(e.key==='+'||e.key==='=')$('#zoom-in').click();if(e.key==='-')$('#zoom-out').click();if(e.key.toLowerCase()==='m')startMark();});
window.addEventListener('resize',()=>{positionImages();});window.addEventListener('beforeunload',e=>{if(noteDraft||intentDraft||manualDraft||localDirty){e.preventDefault();e.returnValue='';}});
for(const control of $$('#versions-button,#mark-button,#add-note,#export-button,#coordinate-note,#context-button,#copy-project,#intent-input,#trial-button,#local-trial,[data-view]'))control.disabled=true;
await refresh().catch(e=>{notice(e.message);$('#save-state').textContent='连接未就绪';$('#image-empty').hidden=false;});
setInterval(async()=>{if(busy||noteDraft||intentDraft||document.hidden||document.activeElement?.matches('input,textarea')||$('dialog[open]'))return;try{const next=await json('project');if(next.revision!==project?.revision){const changes=next.currentId!==project.currentId||JSON.stringify(next.candidates.map(c=>c.id))!==JSON.stringify(project.candidates.map(c=>c.id));chooseNewCandidate(project,next);project=next;renderState();if(changes){zoom=null;pan={x:0,y:0};await loadImages();}}$('#save-state').classList.remove('warning');}catch{$('#save-state').textContent='连接中断 · 编辑已保存';}},2000);
