import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,readFile,writeFile,rm,mkdir,utimes} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';
import {createRequire} from 'node:module';import {fileURLToPath} from 'node:url';
const sharp=createRequire(new URL('../skills/photo-retouch/package.json',import.meta.url))('sharp');
import {initProject,loadProject,currentVersion,createCandidate,acceptCandidate,discardCandidate,restoreVersion,saveNote,deleteNote,setIntent,hash,recordExport} from '../skills/photo-retouch/scripts/project.mjs';
import {renderFrame,exportPhoto,previewPhoto} from '../skills/photo-retouch/scripts/render.mjs';
import {serveProject} from '../skills/photo-retouch/scripts/server.mjs';
import {combineSettings,renderPixels} from '../skills/photo-retouch/scripts/engine/editor-engine.js';
const photo=fileURLToPath(new URL('./fixtures/quality/portrait.png',import.meta.url));
async function fixture(t,image=photo){const root=await mkdtemp(path.join(os.tmpdir(),'guangjian-local-')),folder=path.join(root,'photo');t.after(()=>rm(root,{recursive:true,force:true}));await initProject(image instanceof URL?fileURLToPath(image):image,folder,{intent:'保留真实肤色'});return folder;}
const plan=(p,settings,extra={})=>({revision:p.revision,baseVersion:p.currentId,name:'自然版',settings,...extra});
test('local project preserves source bytes and normalizes EXIF direction once',async t=>{const folder=await fixture(t,new URL('./fixtures/import/orientation-6.jpg',import.meta.url));const p=await loadProject(folder),bytes=await readFile(new URL('./fixtures/import/orientation-6.jpg',import.meta.url));assert.equal(hash(await readFile(path.join(folder,'source','original.bin'))),hash(bytes));const r=await renderFrame(folder);const expected=await sharp(bytes).rotate().metadata();assert.equal(r.width,p.source.width);assert.equal(r.height,p.source.height);assert.notEqual(expected.width,p.source.width);await assert.rejects(initProject(photo,folder),{code:'PROJECT_EXISTS'});});
test('local absolute targets preserve styles and other edits without duplicate compensation',async t=>{const folder=await fixture(t);let p=await loadProject(folder);const a=await createCandidate(folder,plan(p,{exposure:.2},{style:{id:'quiet-film',amount:50}})).catch(async e=>{if(e.code!=='UNKNOWN_STYLE')throw e;const {presets}=await import('../skills/photo-retouch/scripts/engine/presets.js');return createCandidate(folder,plan(p,{exposure:.2},{style:{id:presets[0].id,amount:50}}));});assert.equal((await loadProject(folder)).currentId,p.currentId);await acceptCandidate(folder,{id:a.candidate.id});p=await loadProject(folder);const b=await createCandidate(folder,plan(p,{exposure:.3,shadows:8}));assert.equal(b.candidate.state.settings.exposure,.3);assert.deepEqual(b.candidate.state.style,a.candidate.state.style);await discardCandidate(folder,{id:b.candidate.id});assert.equal(currentVersion(await loadProject(folder)).state.settings.exposure,.2);});
test('candidate retries are idempotent and incompatible repeated request IDs fail',async t=>{const folder=await fixture(t),p=await loadProject(folder),value=plan(p,{shadows:8},{requestId:'same-operation'});const first=await createCandidate(folder,value),second=await createCandidate(folder,value);assert.equal(first.candidate.id,second.candidate.id);assert.equal((await loadProject(folder)).candidates.length,1);await assert.rejects(createCandidate(folder,{...value,settings:{shadows:10}}),{code:'REQUEST_CONFLICT'});});
test('latest intent and comments invalidate old candidates while concurrent writes do not lose work',async t=>{const folder=await fixture(t);let p=await loadProject(folder);const note=await saveNote(folder,{revision:p.revision,rect:{x:.3,y:.1,width:.3,height:.3},note:'人物暗'});p=await loadProject(folder);const c=await createCandidate(folder,plan(p,{shadows:8}));await setIntent(folder,{intent:'保留低调氛围'});await assert.rejects(acceptCandidate(folder,{id:c.candidate.id}),{code:'STALE_CANDIDATE'});p=await loadProject(folder);const results=await Promise.allSettled([createCandidate(folder,plan(p,{highlights:-8})),saveNote(folder,{revision:p.revision,id:note.note.id,note:'保留这里'})]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(results.filter(r=>r.status==='rejected')[0].reason.code,'STALE_REVISION');assert.equal((await loadProject(folder)).intent,'保留低调氛围');});
test('accepted local mask snapshots survive annotation deletion, and protected regions resist crop',async t=>{const folder=await fixture(t);let p=await loadProject(folder);const n=await saveNote(folder,{rect:{x:.3,y:.1,width:.3,height:.3},note:'面部',protect:true});p=await loadProject(folder);await assert.rejects(createCandidate(folder,plan(p,{}, {crop:{x:0,y:.5,width:1,height:.5}})),{code:'PROTECTED_CROP'});const c=await createCandidate(folder,plan(p,{}, {locals:[{annotationId:n.note.id,settings:{exposure:.4},feather:.6,maskType:'radial'}]}));await acceptCandidate(folder,{id:c.candidate.id});const before=await renderFrame(folder);await deleteNote(folder,{id:n.note.id});const after=await renderFrame(folder);assert.equal(before.pixelHash,after.pixelHash);assert.equal(currentVersion(await loadProject(folder)).state.locals[0].note,'面部');await restoreVersion(folder,{id:p.versions[0].id});assert.equal(currentVersion(await loadProject(folder)).state.locals.length,0);});
test('PNG preview and export use exactly the same rendered pixels and do not overwrite files',async t=>{const folder=await fixture(t);let p=await loadProject(folder);const c=await createCandidate(folder,plan(p,{grain:12,sharpen:20,denoise:15,warmth:4},{crop:{x:.1,y:.05,width:.8,height:.9,angle:2}}));await assert.rejects(exportPhoto(folder,c.candidate.id),{code:'UNACCEPTED_EXPORT'});await acceptCandidate(folder,{id:c.candidate.id});const frame=await renderFrame(folder,c.candidate.id,{maxSide:8192}),output=path.join(folder,'exports','final.png'),file=await exportPhoto(folder,c.candidate.id,{output});const actual=await sharp(file.path).ensureAlpha().raw().toBuffer({resolveWithObject:true});assert.equal(hash(actual.data),frame.pixelHash);assert.deepEqual([actual.info.width,actual.info.height],[frame.width,frame.height]);assert.equal(file.pixelHash,frame.pixelHash);await assert.rejects(exportPhoto(folder,c.candidate.id,{output}),{code:'OUTPUT_EXISTS'});await recordExport(folder,file);assert.equal((await loadProject(folder)).exports[0].versionId,c.candidate.id);});
test('standalone pixel renderer matches web engine and detects changed project source',async t=>{const folder=await fixture(t);const source=await renderFrame(folder);let p=await loadProject(folder);const c=await createCandidate(folder,plan(p,{highlights:-15,shadows:8,grain:7}));const rendered=await renderFrame(folder,c.candidate.id);assert.equal(hash(Buffer.from(renderPixels(source.pixels,source.width,source.height,c.candidate.state.settings))),rendered.pixelHash);await writeFile(path.join(folder,'source','original.bin'),'changed');await assert.rejects(renderFrame(folder),{code:'SOURCE_CHANGED'});});
test('local server authenticates sessions, rejects foreign origins, and restores persisted project',async t=>{const folder=await fixture(t);const runtime=await serveProject(folder,{quiet:true});t.after(()=>runtime.close());const base=`http://127.0.0.1:${runtime.session.port}`,token=new URLSearchParams(new URL(runtime.session.url).hash.slice(1)).get('token');assert.equal((await fetch(base+'/api/project')).status,401);const headers={'X-Guangjian-Token':token,'Content-Type':'application/json'};assert.equal((await fetch(base+'/api/intent',{method:'POST',headers:{...headers,Origin:'https://foreign.example'},body:JSON.stringify({intent:'侵入'})})).status,403);const state=await(await fetch(base+'/api/project',{headers})).json();assert.equal(state.folder,folder);const n=await(await fetch(base+'/api/note',{method:'POST',headers,body:JSON.stringify({revision:state.revision,rect:{x:.1,y:.1,width:.2,height:.2},note:'保留这处'})})).json();assert.equal(n.note.note,'保留这处');assert.equal((await loadProject(folder)).notes[0].note,'保留这处');const image=await fetch(base+'/api/image?version=current',{headers});assert.equal(image.status,200);assert.equal(image.headers.get('Content-Type'),'image/png');assert.equal((await fetch(base+'/../../.env.local')).status,404);});

test('protected crop accepts safe bounds and region previews show the actual marked pixels',async t=>{const folder=await fixture(t);await saveNote(folder,{rect:{x:.3,y:.1,width:.3,height:.3},note:'面部',protect:true});const p=await loadProject(folder),c=await createCandidate(folder,plan(p,{exposure:.1},{crop:{x:.05,y:.02,width:.9,height:.93,angle:1}}));assert.ok(c.candidate.id);const region={x:.3,y:.1,width:.3,height:.3},raw=await renderFrame(folder,'original',{region});assert.deepEqual([raw.width,raw.height],[155,154]);assert.equal(raw.sourceRect.x,153);assert.equal(raw.regionMode,'crop-final-frame');assert.ok(raw.stats);const circled=await previewPhoto(folder,'original',{showNotes:true}),decoded=await sharp(circled.path).ensureAlpha().raw().toBuffer();assert.notEqual(hash(decoded),circled.pixelHash);assert.equal((await renderFrame(folder,'original')).pixelHash,circled.pixelHash);});

test('interrupted ownerless writes recover and annotation numbers remain stable after deletion',async t=>{const folder=await fixture(t),lock=path.join(folder,'.edit-lock');await mkdir(lock);const old=new Date(Date.now()-10000);await utimes(lock,old,old);await setIntent(folder,{intent:'意外关闭后继续'});const n=await saveNote(folder,{rect:{x:.1,y:.1,width:.2,height:.2},note:'第一处'});await deleteNote(folder,{id:n.note.id});const next=await saveNote(folder,{rect:{x:.3,y:.3,width:.2,height:.2},note:'新位置'});assert.equal(next.note.number,2);assert.equal((await loadProject(folder)).intent,'意外关闭后继续');});

test('refining a visible candidate inherits its style, crop and local masks without accepting it',async t=>{
  const folder=await fixture(t);const n=await saveNote(folder,{rect:{x:.3,y:.1,width:.3,height:.3},note:'脸部自然'});let p=await loadProject(folder);
  const first=await createCandidate(folder,plan(p,{exposure:.4},{style:{id:'quiet-film',amount:30},crop:{x:.05,y:.02,width:.9,height:.95},locals:[{annotationId:n.note.id,settings:{shadows:8}}]}));
  p=await loadProject(folder);const refined=await createCandidate(folder,plan(p,{highlights:-10},{fromCandidate:first.candidate.id}));
  assert.equal(refined.candidate.state.settings.exposure,.4);assert.equal(refined.candidate.refinedFrom,first.candidate.id);
  for(const key of ['style','crop','locals'])assert.deepEqual(refined.candidate.state[key],first.candidate.state[key]);
  assert.equal((await loadProject(folder)).currentId,p.currentId);assert.equal((await loadProject(folder)).candidates.length,2);
  await discardCandidate(folder,{id:refined.candidate.id});assert.ok((await loadProject(folder)).candidates.some(c=>c.id===first.candidate.id));
  await setIntent(folder,{intent:'不要提亮人物'});p=await loadProject(folder);
  await assert.rejects(createCandidate(folder,plan(p,{highlights:-5},{fromCandidate:first.candidate.id})),{code:'STALE_CANDIDATE'});
});
test('lettering can inherit an unaccepted retouch candidate without replacing its photo adjustments',async t=>{
  const folder=await fixture(t);let p=await loadProject(folder);const first=await createCandidate(folder,plan(p,{exposure:.3,highlights:-12}));p=await loadProject(folder);
  const refined=await createCandidate(folder,{revision:p.revision,baseVersion:p.currentId,fromCandidate:first.candidate.id,mode:'lettering',textOverlays:[{id:'caption',text:'A little lighter',style:'airy',font:'sans',weight:400,x:.05,y:.85,width:.7,size:.04,color:'#FFF8EE',background:'#FFF1DD',align:'left',rotation:0,opacity:1,decoration:'none'}]});
  assert.deepEqual(refined.candidate.state.settings,first.candidate.state.settings);assert.equal(refined.candidate.state.textOverlays.length,1);
  await acceptCandidate(folder,{id:refined.candidate.id});assert.equal(currentVersion(await loadProject(folder)).state.settings.exposure,.3);
});

test('missing source produces a recoverable message and restored bytes can render again',async t=>{
  const folder=await fixture(t),file=path.join(folder,'source','original.bin'),bytes=await readFile(file);await rm(file);
  await assert.rejects(renderFrame(folder),e=>e.code==='SOURCE_MISSING'&&!e.message.includes(folder)&&e.message.includes('保留'));
  await writeFile(file,bytes);assert.ok((await renderFrame(folder)).width>0);
  const {localFailure}=await import('../skills/photo-retouch/scripts/project.mjs');const error=localFailure(Object.assign(new Error('EACCES: /private/path'),{code:'EACCES'}));assert.match(error.message,/权限/);assert.equal(error.message.includes('/private'),false);
});
