import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,rm,readFile,writeFile} from 'node:fs/promises';
import os from 'node:os';import path from 'node:path';import {fileURLToPath} from 'node:url';import {createRequire} from 'node:module';
import {initProject,loadProject,createCandidate,acceptCandidate,discardCandidate,restoreVersion,currentVersion,hash} from '../skills/photo-retouch/scripts/project.mjs';
import {renderFrame,exportPhoto} from '../skills/photo-retouch/scripts/render.mjs';
import {cleanTextOverlays} from '../skills/photo-retouch/scripts/text-overlays.mjs';
const sharp=createRequire(new URL('../skills/photo-retouch/package.json',import.meta.url))('sharp');
async function fixture(t){const root=await mkdtemp(path.join(os.tmpdir(),'frameyn-lettering-'));t.after(()=>rm(root,{recursive:true,force:true}));const folder=path.join(root,'photo');await initProject(fileURLToPath(new URL('./fixtures/quality/portrait.png',import.meta.url)),folder);return folder;}
const note={id:'tiny-note',text:'A little joy',style:'sticker',x:.07,y:.78,width:.62,size:.045,decoration:'heart',rotation:-2};
const plan=(p,extra)=>({revision:p.revision,baseVersion:p.currentId,name:'文字点缀版',mode:'lettering',textOverlays:[note],...extra});
test('ordinary retouch remains text-free and lettering requires an explicit mode',async t=>{const folder=await fixture(t),p=await loadProject(folder),before=await renderFrame(folder);assert.deepEqual(currentVersion(p).state.textOverlays,[]);await assert.rejects(createCandidate(folder,{revision:p.revision,baseVersion:p.currentId,textOverlays:[note]}),{code:'LETTERING_MODE_REQUIRED'});assert.equal((await renderFrame(folder)).pixelHash,before.pixelHash);assert.equal((await loadProject(folder)).revision,p.revision);});
test('lettering candidates preserve every retouch setting, and discard / restore retain the clean edition',async t=>{const folder=await fixture(t);let p=await loadProject(folder);const edit=await createCandidate(folder,{revision:p.revision,baseVersion:p.currentId,settings:{exposure:.1,warmth:5},crop:{x:.05,y:.05,width:.9,height:.9}});await acceptCandidate(folder,{id:edit.candidate.id});p=await loadProject(folder);const before=await renderFrame(folder),c=await createCandidate(folder,plan(p));assert.equal((await renderFrame(folder)).pixelHash,before.pixelHash);assert.deepEqual(c.candidate.state.settings,currentVersion(p).state.settings);assert.deepEqual(c.candidate.state.crop,currentVersion(p).state.crop);assert.deepEqual(c.candidate.state.locals,currentVersion(p).state.locals);assert.notEqual((await renderFrame(folder,c.candidate.id)).pixelHash,before.pixelHash);await discardCandidate(folder,{id:c.candidate.id});assert.equal((await renderFrame(folder)).pixelHash,before.pixelHash);p=await loadProject(folder);const accepted=await createCandidate(folder,plan(p));await acceptCandidate(folder,{id:accepted.candidate.id});assert.equal((await loadProject(folder)).choices.at(-1).mode,'lettering');await restoreVersion(folder,{id:p.currentId});assert.equal((await renderFrame(folder)).pixelHash,before.pixelHash);});
test('no-text export is pixel-identical to the retouched photo and does not mutate the lettering edition',async t=>{const folder=await fixture(t);let p=await loadProject(folder);const clean=await renderFrame(folder),c=await createCandidate(folder,plan(p));await acceptCandidate(folder,{id:c.candidate.id});p=await loadProject(folder);const frame=await renderFrame(folder),file=await exportPhoto(folder,'current',{output:path.join(folder,'exports','with.png')}),raw=await sharp(await readFile(file.path)).ensureAlpha().raw().toBuffer();assert.equal(hash(raw),frame.pixelHash);const plain=await exportPhoto(folder,'current',{withoutText:true,output:path.join(folder,'exports','without.png')});assert.equal(plain.pixelHash,clean.pixelHash);assert.equal((await loadProject(folder)).revision,p.revision);assert.equal(currentVersion(await loadProject(folder)).state.textOverlays.length,1);assert.equal((await renderFrame(folder,'current',{withoutText:true})).pixelHash,clean.pixelHash);});
test('bounds / layout failures do not save broken candidates or silently truncate text',async t=>{assert.throws(()=>cleanTextOverlays([{...note,text:'x'.repeat(121)}]),{code:'TEXT_CONTENT'});assert.throws(()=>cleanTextOverlays([{...note,x:.8,width:.4}]),{code:'TEXT_BOUNDS'});assert.throws(()=>cleanTextOverlays([note,note]),{code:'TEXT_ID'});const folder=await fixture(t),p=await loadProject(folder);await assert.rejects(createCandidate(folder,plan(p,{textOverlays:[{...note,y:.94,size:.12,text:'Too close to the edge'}]})),{code:'TEXT_OVERFLOW'});assert.equal((await loadProject(folder)).candidates.length,0);assert.equal((await loadProject(folder)).revision,p.revision);});
test('region previews preserve full-composition placement and scaled frames retain the same layout',async t=>{const folder=await fixture(t),p=await loadProject(folder),c=await createCandidate(folder,plan(p));const full=await renderFrame(folder,c.candidate.id),region=await renderFrame(folder,c.candidate.id,{region:{x:0,y:.5,width:1,height:.5}}),cleanRegion=await renderFrame(folder,'current',{region:{x:0,y:.5,width:1,height:.5}});assert.notEqual(region.pixelHash,cleanRegion.pixelHash);assert.deepEqual(region.textLayout,full.textLayout);const crop=full.sourceRect;const bytes=await sharp(full.png).extract({left:0,top:Math.round(crop.height*.5),width:full.width,height:Math.round(crop.height*.5)}).ensureAlpha().raw().toBuffer();assert.equal(hash(bytes),region.pixelHash);});
test('actual text footprints scale with preview and export size',async t=>{
  const root=await mkdtemp(path.join(os.tmpdir(),'frameyn-text-scale-'));t.after(()=>rm(root,{recursive:true,force:true}));const image=path.join(root,'large.png');await writeFile(image,await sharp(fileURLToPath(new URL('./fixtures/quality/portrait.png',import.meta.url))).resize(1200,800).png().toBuffer());const folder=path.join(root,'photo');await initProject(image,folder);const p=await loadProject(folder),c=await createCandidate(folder,plan(p)),footprints=[];
  for(const maxSide of [512,1200]){const text=await renderFrame(folder,c.candidate.id,{maxSide}),plain=await renderFrame(folder,c.candidate.id,{maxSide,withoutText:true});let minX=text.width,minY=text.height,maxX=0,maxY=0,count=0;for(let i=0;i<text.pixels.length;i+=4){if(Math.max(...[0,1,2].map(k=>Math.abs(text.pixels[i+k]-plain.pixels[i+k])))<12)continue;const x=(i/4)%text.width,y=Math.floor((i/4)/text.width);minX=Math.min(minX,x);maxX=Math.max(maxX,x);minY=Math.min(minY,y);maxY=Math.max(maxY,y);count++;}assert.ok(count>200);footprints.push([minX/text.width,minY/text.height,maxX/text.width,maxY/text.height]);}
  for(let i=0;i<4;i++)assert.ok(Math.abs(footprints[0][i]-footprints[1][i])<.006,`normalized footprint ${i} differs`);
});
