import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,mkdir,writeFile,readFile,rm,stat,utimes} from 'node:fs/promises';
import {fork} from 'node:child_process';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createRequire} from 'node:module';
import {initProject,loadProject,setIntent} from '../skills/photo-retouch/scripts/project.mjs';
import {initCollection,loadCollection} from '../skills/photo-retouch/scripts/collection.mjs';

async function fixture(t,kind){
  const root=await mkdtemp(join(tmpdir(),'framelark-file-lock-')),children=[];
  t.after(async()=>{for(const child of children)if(child.exitCode===null){const ended=new Promise(resolve=>child.once('exit',resolve));child.kill();await ended;}await rm(root,{recursive:true,force:true});});
  const image=join(root,'technical.png'),sharp=createRequire(new URL('../skills/photo-retouch/package.json',import.meta.url))('sharp');await sharp({create:{width:32,height:24,channels:3,background:'#728798'}}).png().toFile(image);
  const folder=join(root,'photo'),lock=join(folder,kind==='project'?'.edit-lock':'.collection-lock');if(kind==='project')await initProject(image,folder);else await initCollection(folder,{images:[image]});
  const worker=join(root,'mutation-worker.mjs'),projectURL=new URL('../skills/photo-retouch/scripts/project.mjs',import.meta.url).href,collectionURL=new URL('../skills/photo-retouch/scripts/collection.mjs',import.meta.url).href;
  await writeFile(worker,`import fs from 'node:fs/promises';import {syncBuiltinESMExports} from 'node:module';const [folder,kind,role]=process.argv.slice(2),lock=folder+'/'+(kind==='project'?'.edit-lock':'.collection-lock'),pid=value=>{try{return JSON.parse(String(value)).pid||Number(value);}catch{return Number(value);}},pause=()=>new Promise(resolve=>process.once('message',resolve)),originalRead=fs.readFile,originalRm=fs.rm,originalOpen=fs.open,originalWrite=fs.writeFile;let held=false;fs.readFile=async(...args)=>{const value=await originalRead(...args);if(role==='B'&&String(args[0])===lock+'/owner'){if(!held){held=true;process.send({type:'stale-observed'});await pause();}else if(pid(value)>0&&pid(value)!==process.pid&&pid(value)!==2147483647)process.send({type:'decision',kind:'live-recheck'});}return value;};fs.rm=async(...args)=>{let owner;if(role==='B'&&String(args[0])===lock)owner=pid(await originalRead(lock+'/owner','utf8').catch(()=>''));const value=await originalRm(...args);if(owner>0&&owner!==process.pid&&owner!==2147483647)process.send({type:'decision',kind:'removed-live-lock'});return value;};fs.open=async(...args)=>{if(role==='A'&&!held&&String(args[0]).includes(kind==='project'?'.project-':'.collection-')){held=true;process.send({type:'write-ready',owner:pid(await originalRead(lock+'/owner','utf8'))});await pause();}return originalOpen(...args);};fs.writeFile=async(...args)=>{if(role==='write-failure'&&!held&&String(args[0])===lock+'/owner'){held=true;await originalWrite(args[0],'',args[2]);throw Object.assign(Error('technical disk-full fixture'),{code:'ENOSPC'});}return originalWrite(...args);};syncBuiltinESMExports();try{const runtime=await import(kind==='project'?${JSON.stringify(projectURL)}:${JSON.stringify(collectionURL)});const result=kind==='project'?role==='A'?await runtime.saveNote(folder,{revision:1,rect:{x:.1,y:.1,width:.2,height:.2},note:'A note'}):await runtime.setIntent(folder,{revision:1,intent:'B intent'}):await runtime.updateCollectionBrief(folder,{revision:1,brief:role==='A'?{theme:'A theme'}:{constraints:['B constraint']}});process.send({type:'result',status:'fulfilled',revision:kind==='project'?result.project.revision:result.revision});}catch(error){process.send({type:'result',status:'rejected',code:error.code,message:error.message});}finally{process.disconnect();}`);
  const launch=role=>{const child=fork(worker,[folder,kind,role],{stdio:['ignore','ignore','ignore','ipc']}),packets=[],waiters=[];children.push(child);child.on('message',packet=>{packets.push(packet);for(const ready of [...waiters])ready();});return {child,next:type=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>{waiters.splice(waiters.indexOf(check),1);reject(Error('worker did not reach '+type));},10000);function check(){const packet=packets.find(p=>p.type===type);if(packet){clearTimeout(timer);waiters.splice(waiters.indexOf(check),1);resolve(packet);}}waiters.push(check);check();})};};
  return {folder,lock,launch};
}
for(const kind of ['project','collection'])test(kind+' stale-lock recovery cannot delete a newly acquired live lock or lose a successful edit',async t=>{
  const f=await fixture(t,kind);await mkdir(f.lock);await writeFile(join(f.lock,'owner'),'2147483647');const b=f.launch('B');await b.next('stale-observed');const a=f.launch('A'),live=await a.next('write-ready');assert.equal(live.owner,a.child.pid);
  b.child.send('allow stale observation');const decision=await b.next('decision');if(decision.kind==='removed-live-lock')await b.next('result');a.child.send('allow first write');const results=await Promise.all([a.next('result'),b.next('result')]);
  assert.equal(results.filter(r=>r.status==='fulfilled').length,1,'the same revision must not commit twice');assert.equal(results.find(r=>r.status==='rejected').code,kind==='project'?'STALE_REVISION':'STALE_COLLECTION');const latest=kind==='project'?await loadProject(f.folder):await loadCollection(f.folder);assert.equal(latest.revision,2);
});
test('a stale empty project owner is recoverable without changing original image bytes',async t=>{
  const f=await fixture(t,'project'),bytes=await readFile(join(f.folder,'source/original.bin'));await mkdir(f.lock);await writeFile(join(f.lock,'owner'),'');const old=new Date(Date.now()-20000);await utimes(f.lock,old,old);const result=await setIntent(f.folder,{revision:1,intent:'recovered'});assert.equal(result.project.intent,'recovered');assert.deepEqual(await readFile(join(f.folder,'source/original.bin')),bytes);await assert.rejects(stat(f.lock),{code:'ENOENT'});
});
for(const kind of ['project','collection'])test(kind+' cleans up its own directory when owner write fails',async t=>{
  const f=await fixture(t,kind),result=await f.launch('write-failure').next('result');assert.equal(result.status,'rejected');assert.equal(result.code,'ENOSPC');await assert.rejects(stat(f.lock),{code:'ENOENT'});
});
