import test from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,mkdir,readFile,writeFile,cp,rm,chmod,stat} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join,dirname,delimiter} from 'node:path';import {spawnSync,execFileSync} from 'node:child_process';import {fileURLToPath} from 'node:url';
const repository=fileURLToPath(new URL('../../',import.meta.url));
async function fixture(t){const root=await mkdtemp(join(tmpdir(),'framelark-local-install-'));t.after(()=>rm(root,{recursive:true,force:true}));const source=join(root,'source'),prior=join(root,'prior-market'),state=join(root,'codex-state.json'),bin=join(root,'bin');await mkdir(source);await mkdir(bin);const put=async(path,value)=>{await mkdir(dirname(join(source,path)),{recursive:true});await writeFile(join(source,path),value);};
 for(const path of ['plugin.json','.codex-plugin/plugin.json','.agents/plugins/marketplace.json','plugins/framelark-eye/.codex-plugin/plugin.json'])await put(path,await readFile(join(repository,path)));
 for(const name of ['build-framelark-plugin.mjs','install-framelark-plugin.mjs','install-framelark-release.mjs','install-photography-eye.mjs','installation-guide.mjs'])await put('scripts/'+name,await readFile(join(repository,'scripts',name)));
 await put('assets/framelark-avatar.png','icon');for(const name of ['photo-retouch','photography-eye','photo-series'])await put('skills/'+name+'/SKILL.md','---\nname: '+name+'\n---\nNew maintained content.');await put('skills/photography-eye/assets/xiaozhen.png','icon');
 await put('skills/photo-retouch/scripts/setup.mjs',`import {mkdirSync,writeFileSync} from 'node:fs';import {fileURLToPath} from 'node:url';const root=fileURLToPath(new URL('../',import.meta.url));if(process.env.FRAMELARK_FIXTURE_FAIL==='stage'||process.env.FRAMELARK_FIXTURE_FAIL==='installed'&&root.includes('/cache/'))process.exit(1);mkdirSync(root+'/node_modules',{recursive:true});writeFileSync(root+'/node_modules/ready','native fixture');if(process.env.FRAMELARK_FIXTURE_UI_SOURCE==='installed'&&root.includes('/cache/')){const fs=await import('node:fs'),file=process.env.FRAMELARK_FIXTURE_STATE,state=JSON.parse(fs.readFileSync(file));state.market.marketplaceSource.source='/later/user/source';fs.writeFileSync(file,JSON.stringify(state));}if(process.env.FRAMELARK_FIXTURE_UI_DISABLE==='1'&&!root.includes('/cache/')){const fs=await import('node:fs'),file=process.env.FRAMELARK_FIXTURE_STATE,state=JSON.parse(fs.readFileSync(file));state.installed[0].enabled=false;fs.writeFileSync(file,JSON.stringify(state));}`);
 execFileSync('git',['init','--quiet'],{cwd:source});execFileSync('git',['add','.'],{cwd:source});
 const old=join(prior,'framelark');await mkdir(join(old,'.codex-plugin'),{recursive:true});await writeFile(join(old,'.codex-plugin/plugin.json'),JSON.stringify({name:'framelark',version:'0.1.12',skills:'./skills/'}));
 for(const name of ['photo-retouch','photography-eye','photo-series']){await mkdir(join(old,'skills',name),{recursive:true});await writeFile(join(old,'skills',name,'SKILL.md'),'---\nname: '+name+'\n---\nOriginal installed knowledge.');}
 await mkdir(join(prior,'.agents/plugins'),{recursive:true});await writeFile(join(prior,'.agents/plugins/marketplace.json'),JSON.stringify({name:'framelark',plugins:[{name:'framelark',source:{source:'local',path:'./framelark'}}]}));const oldCache=join(root,'cache/framelark/0.1.12');await cp(old,oldCache,{recursive:true});
 const initial={market:{name:'framelark',root:prior,marketplaceSource:{sourceType:'local',source:prior}},installed:[{pluginId:'framelark@framelark',version:'0.1.12',installed:true,enabled:true,installedPath:oldCache}]};await writeFile(state,JSON.stringify(initial));
 await writeFile(join(bin,'codex'),`#!/usr/bin/env node
 const fs=require('node:fs'),path=require('node:path'),args=process.argv.slice(2),statePath=${JSON.stringify(state)},prior=${JSON.stringify(prior)},root=${JSON.stringify(root)},state=JSON.parse(fs.readFileSync(statePath));const save=()=>fs.writeFileSync(statePath,JSON.stringify(state));
 if(args.includes('--help')){console.log('{}');process.exit(0);}
 if(args[1]==='marketplace'&&args[2]==='list'&&process.env.FRAMELARK_FIXTURE_QUERY_FAIL==='1'&&state.market?.root!==prior){console.error('cannot read registration during recovery');process.exit(1);}
 else if(args[1]==='marketplace'&&args[2]==='list')console.log(JSON.stringify({marketplaces:state.market?[state.market]:[]}));
 else if(args[1]==='marketplace'){if(args[2]==='remove')state.market=null;else if(args[2]==='add'){if(process.env.FRAMELARK_FIXTURE_RESTORE_FAIL==='1'&&args[3]===prior){console.error('original marketplace restore failed');process.exit(1);}state.market={name:'framelark',root:args[3],marketplaceSource:{sourceType:'local',source:args[3]}};}save();console.log('{}');}
 else if(args[1]==='list')console.log(JSON.stringify({installed:state.installed}));
 else if(args[1]==='remove'){state.installed=state.installed.filter(p=>p.pluginId!==args[2]);save();console.log('{}');}
 else if(args[1]==='add'){if(process.env.FRAMELARK_FIXTURE_UI_SOURCE==='plugin-add'&&state.market.root!==prior){state.market.marketplaceSource.source='/later/user/source';save();console.error('plugin add returned no installation');process.exit(1);}const name=args[2].split('@')[0],catalog=JSON.parse(fs.readFileSync(path.join(state.market.root,'.agents/plugins/marketplace.json'))),entry=catalog.plugins.find(p=>p.name===name),src=path.resolve(state.market.root,entry.source.path),manifest=JSON.parse(fs.readFileSync(path.join(src,'.codex-plugin/plugin.json'))),installedPath=path.join(root,'cache',name,manifest.version);fs.mkdirSync(path.dirname(installedPath),{recursive:true});if(process.env.FRAMELARK_FIXTURE_DELETE_OLD==='1'){for(const old of state.installed)if(old.installedPath!==installedPath)fs.rmSync(old.installedPath,{recursive:true,force:true});}fs.cpSync(src,installedPath,{recursive:true});state.installed=state.installed.filter(p=>p.pluginId!==args[2]);state.installed.push({pluginId:args[2],version:manifest.version,installed:true,enabled:true,installedPath});save();if(['lost-reply','lost-reply-disable','lost-reply-remove'].includes(process.env.FRAMELARK_FIXTURE_UI_SOURCE)&&state.market.root!==prior){if(process.env.FRAMELARK_FIXTURE_UI_SOURCE==='lost-reply')state.installed[0].version='0.1.99';state.installed[0].enabled=false;if(process.env.FRAMELARK_FIXTURE_UI_SOURCE==='lost-reply-remove')state.installed=[];save();console.error('plugin add reply lost');process.exit(1);}console.log(JSON.stringify({pluginId:args[2],installedPath}));}else process.exit(1);
 `);await chmod(join(bin,'codex'),0o755);const env={...process.env,PATH:bin+delimiter+process.env.PATH,FRAMELARK_CODEX_BIN:join(bin,'codex'),FRAMELARK_FIXTURE_STATE:state};
 return {root,source,prior,state,initial,run:extra=>spawnSync(process.execPath,[join(source,'scripts/install-framelark-plugin.mjs')],{cwd:source,env:{...env,...extra},encoding:'utf8',timeout:40000})};}
test('local dependency staging failure leaves the original source and installation unchanged and suggests local retry',async t=>{const f=await fixture(t),result=f.run({FRAMELARK_FIXTURE_FAIL:'stage'});assert.notEqual(result.status,0);assert.deepEqual(JSON.parse(await readFile(f.state)),f.initial);assert.match(result.stderr,/plugin:install:local/);});
test('installed local dependency failure restores the original market and original plugin version',async t=>{const f=await fixture(t),result=f.run({FRAMELARK_FIXTURE_FAIL:'installed'});assert.notEqual(result.status,0);const after=JSON.parse(await readFile(f.state));assert.deepEqual(after.market,f.initial.market);assert.equal(after.installed[0].version,'0.1.12');assert.equal(after.installed[0].enabled,true);assert.match(await readFile(join(after.installed[0].installedPath,'skills/photo-retouch/SKILL.md'),'utf8'),/Original/);assert.match(result.stderr,/plugin:install:local/);});
test('local rollback failure preserves a private recovery record and reports both failures',async t=>{const f=await fixture(t),result=f.run({FRAMELARK_FIXTURE_FAIL:'installed',FRAMELARK_FIXTURE_RESTORE_FAIL:'1'});assert.notEqual(result.status,0);assert.match(result.stderr,/恢复.*未完成/);const record=result.stderr.match(/恢复记录：([^\n]+)/)?.[1];assert.ok(record,result.stderr);const data=JSON.parse(await readFile(record,'utf8'));assert.equal(data.marketplace.root,f.prior);assert.equal(data.plugin.version,'0.1.12');if(process.platform!=='win32')assert.equal((await stat(record)).mode&0o777,0o600);});
test('local installer preserves a disabled existing plugin before any source replacement',async t=>{const f=await fixture(t);f.initial.installed[0].enabled=false;await writeFile(f.state,JSON.stringify(f.initial));const result=f.run({});assert.notEqual(result.status,0);assert.deepEqual(JSON.parse(await readFile(f.state)),f.initial);assert.match(result.stderr,/停用/);});
test('local installation succeeds with verified maintained contents and enabled state',async t=>{const f=await fixture(t),result=f.run({});assert.equal(result.status,0,result.stderr);const data=JSON.parse(result.stdout);assert.equal(data.ok,true);assert.equal(data.enabled,true);assert.equal(data.retouchDependencies,'ready');assert.match(await readFile(join(data.installedPath,'skills/photo-retouch/SKILL.md'),'utf8'),/New maintained/);});

test('an unreadable registration during local recovery retains the source and private recovery record',async t=>{const f=await fixture(t),result=f.run({FRAMELARK_FIXTURE_FAIL:'installed',FRAMELARK_FIXTURE_QUERY_FAIL:'1'});assert.notEqual(result.status,0);assert.match(result.stderr,/恢复.*未完成/);const record=result.stderr.match(/恢复记录：([^\n]+)/)?.[1];assert.ok(record,result.stderr);await readFile(record);const after=JSON.parse(await readFile(f.state));await stat(after.market.root);});

test('local failed update restores native RAW and additional user files after the old cache was deleted',async t=>{const f=await fixture(t),old=f.initial.installed[0].installedPath;await mkdir(join(old,'skills/photo-retouch/node_modules'),{recursive:true});await writeFile(join(old,'skills/photo-retouch/node_modules/ready'),'prior-native-ready');await mkdir(join(old,'.raw-venv/bin'),{recursive:true});await writeFile(join(old,'.raw-venv/bin/pip'),'#!'+old+'/.raw-venv/bin/python\n');await writeFile(join(old,'personal.txt'),'preserved user data');const result=f.run({FRAMELARK_FIXTURE_FAIL:'installed',FRAMELARK_FIXTURE_DELETE_OLD:'1'});assert.notEqual(result.status,0);assert.equal(await readFile(join(old,'skills/photo-retouch/node_modules/ready'),'utf8'),'prior-native-ready');assert.equal(await readFile(join(old,'.raw-venv/bin/pip'),'utf8'),'#!'+old+'/.raw-venv/bin/python\n');assert.equal(await readFile(join(old,'personal.txt'),'utf8'),'preserved user data');});

test('local staging does not replace a later user disable choice',async t=>{const f=await fixture(t),result=f.run({FRAMELARK_FIXTURE_UI_DISABLE:'1'});assert.notEqual(result.status,0);assert.match(result.stderr,/变化|选择/);const state=JSON.parse(await readFile(f.state));assert.deepEqual(state.market,f.initial.market);assert.equal(state.installed[0].enabled,false);assert.equal(state.installed[0].version,'0.1.12');});


test('local success is withheld if the selected source changes during installed setup',async t=>{const f=await fixture(t),result=f.run({FRAMELARK_FIXTURE_UI_SOURCE:'installed'});assert.notEqual(result.status,0);assert.match(result.stderr,/变化|选择/);assert.equal(JSON.parse(await readFile(f.state)).market.marketplaceSource.source,'/later/user/source');});


test('local recovery preserves a later source even when plugin add fails before returning',async t=>{const f=await fixture(t),result=f.run({FRAMELARK_FIXTURE_UI_SOURCE:'plugin-add'});assert.notEqual(result.status,0);assert.match(result.stderr,/恢复.*未完成/);assert.equal(JSON.parse(await readFile(f.state)).market.marketplaceSource.source,'/later/user/source');});


test('local recovery preserves unknown version and disable choices after a lost plugin-add reply',async t=>{const f=await fixture(t),result=f.run({FRAMELARK_FIXTURE_UI_SOURCE:'lost-reply'});assert.notEqual(result.status,0);assert.match(result.stderr,/恢复.*未完成/);const selected=JSON.parse(await readFile(f.state)).installed[0];assert.equal(selected.version,'0.1.99');assert.equal(selected.enabled,false);});


test('local recovery preserves a disable action on the new version before a lost plugin-add reply',async t=>{const f=await fixture(t),result=f.run({FRAMELARK_FIXTURE_UI_SOURCE:'lost-reply-disable'});assert.notEqual(result.status,0);assert.match(result.stderr,/恢复.*未完成/);const selected=JSON.parse(await readFile(f.state)).installed[0];assert.equal(selected.version,'0.1.14');assert.equal(selected.enabled,false);});


test('local recovery preserves a remove action before a lost plugin-add reply',async t=>{const f=await fixture(t),result=f.run({FRAMELARK_FIXTURE_UI_SOURCE:'lost-reply-remove'});assert.notEqual(result.status,0);assert.match(result.stderr,/恢复.*未完成/);assert.deepEqual(JSON.parse(await readFile(f.state)).installed,[]);});
