import {adjustmentKeys,limits} from '../editor-engine.js';
import {identifier,object,number,fail} from './values.js';
const families={tone:['contrast','highlights','shadows','whites','blacks','curveShadows','curveMidtones','curveHighlights','dehaze','fade'],color:['warmth','tint','saturation','vibrance','monochrome','orangeHue','greenHue','blueHue','orangeSaturation','greenSaturation','blueSaturation','orangeLuminance','greenLuminance','blueLuminance'],detail:['texture','clarity','sharpen','denoise'],finish:['vignette','grain']};
const names={exposure:'曝光',tone:'影调',color:'色彩',detail:'细节',finish:'氛围'};
const definitions=new Map();
export function registerPixelTool(tool){identifier(tool.id);if(!Number.isInteger(tool.version)||tool.version<2||definitions.has(tool.id+'@'+tool.version)||!tool.defaults||!tool.bounds||tool.space!=='linear-srgb'||!Number.isInteger(tool.kernelVersion)||tool.kernelVersion<1||!Number.isInteger(tool.halo)||tool.halo<0||tool.halo>64||!Array.isArray(tool.writes)||tool.writes.some(key=>!adjustmentKeys.includes(key))||(!Object.hasOwn(names,tool.id)&&typeof tool.kernel!=='function'))fail('TOOL_DEFINITION_INVALID','像素工具版本或参数契约无效。');for(const [key,value] of Object.entries(tool.defaults)){if(tool.choices?.[key]){if(!tool.choices[key].includes(value))fail('TOOL_DEFINITION_INVALID','像素工具中性参数无效。');}else if(!tool.bounds[key]||!Number.isFinite(value)||value<tool.bounds[key][0]||value>tool.bounds[key][1])fail('TOOL_DEFINITION_INVALID','像素工具参数边界无效。');}const frozen={...tool,defaults:Object.freeze({...tool.defaults}),bounds:Object.freeze(Object.fromEntries(Object.entries(tool.bounds).map(([key,value])=>[key,Object.freeze([...value])]))),choices:tool.choices?Object.freeze(Object.fromEntries(Object.entries(tool.choices).map(([key,value])=>[key,Object.freeze([...value])]))):undefined,writes:Object.freeze([...tool.writes])};definitions.set(tool.id+'@'+tool.version,Object.freeze(frozen));return frozen;}
registerPixelTool({id:'exposure',version:2,title:names.exposure,defaults:{ev:0,headroomPolicy:'limit-positive-gain'},bounds:{ev:[-3,3]},choices:{headroomPolicy:['limit-positive-gain','unbounded']},space:'linear-srgb',kernelVersion:1,halo:0,writes:['exposure']});
for(const [id,keys] of Object.entries(families))registerPixelTool({id,version:2,title:names[id],defaults:Object.fromEntries(keys.map(key=>[key,0])),bounds:Object.fromEntries(keys.map(key=>[key,limits[key]||[-75,75]])),space:'linear-srgb',kernelVersion:1,halo:id==='detail'?16:0,writes:keys});
export function pixelTool(id,version){const value=definitions.get(id+'@'+version);if(!value)fail('TOOL_VERSION_UNSUPPORTED','这个工具版本尚不能作为可编辑像素步骤执行。',{tool:id,version});return value;}
export function parametersFor(id,version,value,{partial=false}={}){const tool=pixelTool(id,version);object(value,Object.keys(tool.defaults),partial?[]:Object.keys(tool.defaults));const parameters={...tool.defaults,...value};for(const [key,v] of Object.entries(parameters)){if(tool.choices?.[key]){if(!tool.choices[key].includes(v))fail('INVALID_DOCUMENT','工具参数选项无效。');}else number(v,...tool.bounds[key]);}return parameters;}
export function pixelCapabilities(){return {pipeline:'edit-stack-linear-v2',kernelVersion:1,maxSteps:64,maxCommands:24,maxMaskDepth:8,tools:[...definitions.values()].map(tool=>({id:tool.id,title:tool.title,version:tool.version,kernelVersion:tool.kernelVersion,space:tool.space,halo:tool.halo,defaults:{...tool.defaults},parameters:{type:'object',properties:Object.fromEntries(Object.entries(tool.defaults).map(([key])=>[key,tool.choices?.[key]?{type:'string',enum:tool.choices[key]}:{type:'number',minimum:tool.bounds[key][0],maximum:tool.bounds[key][1]}])),required:Object.keys(tool.defaults),additionalProperties:false}}))};}
export function neutralStep(step){const tool=pixelTool(step.tool,step.toolVersion);return Object.entries(tool.defaults).every(([key,value])=>key==='headroomPolicy'||step.parameters[key]===value);}
export function splitSettings(settings){const result=[];if(settings.exposure)result.push({tool:'exposure',toolVersion:2,parameters:{ev:settings.exposure,headroomPolicy:'limit-positive-gain'}});for(const [tool,keys] of Object.entries(families)){const parameters=Object.fromEntries(keys.map(key=>[key,settings[key]||0]));if(Object.values(parameters).some(Boolean))result.push({tool,toolVersion:2,parameters});}if(Object.keys(settings).some(key=>!adjustmentKeys.includes(key)))fail('INVALID_DOCUMENT','风格包含未知效果。');return result;}
